Repository mozilla/fxa-content-server, pull requests merged in 2018-06, with the labels that each got.

#6245 fix(email-first): Handle email-first refresh on /signup, /signin
  app/scripts/views/mixins/email-first-experiment-mixin.js
  app/tests/spec/views/mixins/email-first-experiment-mixin.js
  tests/functional/fx_firstrun_v2_email_first.js
Labels: waffle:active

#6246 fix(dep): update to fxa-crypto-relier 2.3.0
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#6248 feat(Lockbox): Add newest Lockbox app redirect_uri
  server/lib/configuration.js
Labels: train-113, waffle:active

#6252 fix(authorization): Minor updates for /authorization endpoint
  app/scripts/views/authorization.js
  app/tests/spec/views/authorization.js
  tests/functional/oauth_query_param_validation.js
Labels: train-113, waffle:active

#6255 fix(teamcity): fix small potential race on teamcity test kickoff
  tests/teamcity/run.sh
Labels: waffle:active

#6253 Train 113 uplift
  CHANGELOG.md
  app/scripts/views/authorization.js
  app/tests/spec/views/authorization.js
  package.json
  tests/functional/oauth_query_param_validation.js
Labels: waffle:active

#6256 chore(totp): enable totp for 100% of users
  app/scripts/lib/experiments/grouping-rules/totp.js
Labels: train-113, waffle:review

#6260 fix(css): make "show password" button background white on blur
  app/styles/modules/_password-row.scss
Labels: waffle:active

#6265 Uplift Train 113-3
  CHANGELOG.md
  app/scripts/lib/experiments/grouping-rules/totp.js
  package.json
Labels: waffle:active

#6238 fix(refresh): adds `Last checked:` as tooltip
  app/scripts/templates/settings/emails.mustache
  app/scripts/templates/settings/two_step_authentication.mustache
  app/scripts/templates/settings/upgrade_session.mustache
  app/scripts/views/mixins/last-checked-time-mixin.js
  app/scripts/views/mixins/upgrade-session-mixin.js
  app/scripts/views/settings/emails.js
  app/scripts/views/settings/two_step_authentication.js
  app/tests/spec/views/mixins/last-checked-time-mixin.js
  app/tests/test_start.js
Labels: train-114, waffle:review

#6239 fix(codes): adds more support for assistive technologies
  app/scripts/templates/settings/recovery_codes.mustache
  app/scripts/templates/settings/two_step_authentication.mustache
  app/scripts/views/settings/two_step_authentication.js
Labels: train-114, waffle:review

#6270 feat(websessions): reenable websessions
  app/scripts/lib/experiments/grouping-rules/index.js
  app/scripts/lib/experiments/grouping-rules/sessions.js
  app/scripts/templates/settings/clients.mustache
  app/scripts/views/settings/clients.js
  app/tests/spec/lib/experiments/grouping-rules/index.js
  app/tests/spec/lib/experiments/grouping-rules/sessions.js
  app/tests/test_start.js
  npm-shrinkwrap.json
  tests/functional/settings_clients.js
Labels: waffle:active

#6269 fix(codes): use number pad when entering totp code
  app/scripts/templates/settings/two_step_authentication.mustache
  app/scripts/templates/sign_in_totp_code.mustache
  app/scripts/views/elements/totp-code-input.js
  app/tests/spec/views/elements/totp-code-input.js
  tests/functional/sign_in_totp.js
Labels: waffle:active

#6272 Allow lockbox to request the "oldsync" OAuth scope.
  server/lib/configuration.js
Labels: waffle:review

#6271 fix(oauth): translate oauth permissions
  app/scripts/views/permissions.js
  app/tests/spec/views/permissions.js
Labels: waffle:active

#6274 fix(style): Fix input element zoom issues on iOS.
  app/styles/_variables.scss
Labels: train-114, waffle:active

#6275 chore(deps): Use native promises instead of bluebird.
  npm-shrinkwrap.json
  package.json
  server/lib/legal-templates.js
  tests/teamcity/install-npm-deps.sh
Labels: waffle:active

#6278 fix(docker): let's do only one npm version override
  Dockerfile-build
Labels: waffle:active

#6280 fix(l10n): Enable nb-NO locale by updating fxa-shared
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#6276 Merge train-114 into master
  AUTHORS
  CHANGELOG.md
  Dockerfile-build
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#6283 fix(teamcity): add config file for stable3
  tests/teamcity/stable3
Labels: waffle:active

#6285 fix(typo): Moved the period outside of link
  app/scripts/templates/settings/two_step_authentication.mustache
Labels: waffle:active

#6287 refactor(module): Remove AMD wrapper from SignUpPasswordView
  app/scripts/views/sign_up_password.js
Labels: train-115, waffle:review

#6292 fix(timers): Always destroy timers created in view.setTimeout.
  app/scripts/views/mixins/timer-mixin.js
  app/tests/spec/views/mixins/timer-mixin.js
Labels: train-115, waffle:review

#6293 fix(test): Fix the sign_up->afterVisible test
  app/tests/lib/helpers.js
  app/tests/spec/views/sign_up.js
Labels: train-115, waffle:review

#6294 refactor(experiment): Extract a common `isTestEmail` function for all experiments.
  app/scripts/lib/experiments/grouping-rules/base.js
  app/scripts/lib/experiments/grouping-rules/send-sms-install-link.js
  app/scripts/lib/experiments/grouping-rules/totp.js
  app/tests/spec/lib/experiments/grouping-rules/base.js
Labels: waffle:active

#6297 Add TOTP experiment to manual experiment group
  app/scripts/lib/experiment.js
  app/scripts/views/sign_in_totp_code.js
  app/tests/spec/views/sign_in_totp_code.js
Labels: train-114, waffle:active

#6298 Merge v1.113.4 into train-114
  CHANGELOG.md
  server/lib/configuration.js
Labels: waffle:active

#6301 Merge Train 114 to master
  CHANGELOG.md
  app/scripts/lib/experiment.js
  app/scripts/views/sign_in_totp_code.js
  app/tests/spec/views/sign_in_totp_code.js
  package.json
  server/lib/configuration.js
Labels: waffle:active

#6302 refactor(tooltip): Extract the "one tooltip at a time" logic
  app/scripts/views/mixins/one-visible-of-type-mixin.js
  app/scripts/views/tooltip.js
  app/tests/spec/views/mixins/one-visible-of-type-mixin.js
  app/tests/test_start.js
Labels: train-115, waffle:review

#6303 refactor(module): Remove the AMD wrapper on lib/experiment.js
  app/scripts/lib/experiment.js
Labels: train-115, waffle:review

#6300 fix(metrics): prevent reset-password from clobbering mixed-in events
  app/scripts/views/reset_password.js
  app/tests/spec/views/reset_password.js
Labels: waffle:review

#6307 fix(codes): use new line carriage return and spaces to separate recovery codes
  app/scripts/views/settings/recovery_codes.js
Labels: waffle:review

#6315 Release v1.115.0
  AUTHORS
  CHANGELOG.md
  package.json
Labels: waffle:active
