Repository mozilla/fxa-content-server, pull requests merged in 2018-12, with the labels that each got.

#6739 feat(coppa): Put COPPA behind a feature flag.
  app/scripts/lib/app-start.js
  app/scripts/models/reliers/relier.js
  app/scripts/views/mixins/coppa-mixin.js
  app/tests/spec/models/reliers/relier.js
  app/tests/spec/views/mixins/coppa-mixin.js
  server/lib/configuration.js
  server/lib/routes/get-index.js
  tests/functional/lib/selectors.js
  tests/functional/sign_up.js
  tests/functional/sync_v3_email_first.js
Labels: train-127, waffle:review

#6733 feat(metrics): add deviceId to the resume token
  app/scripts/lib/app-start.js
  app/scripts/lib/metrics.js
  app/scripts/models/flow.js
  app/scripts/models/resume-token.js
  app/tests/spec/lib/metrics.js
  app/tests/spec/models/flow.js
Labels: train-127, waffle:review

#6734 chore(verify): remove server side verification
  app/scripts/models/account.js
  app/scripts/models/user.js
  app/scripts/views/complete_sign_up.js
  app/tests/spec/models/account.js
  app/tests/spec/views/complete_sign_up.js
  server/lib/routes.js
  server/lib/routes/get-verify-email.js
  tests/server/routes/get-verify-email.js
  tests/tests_server.js
Labels: waffle:review

#6735 chore(code): enable token code for 25% of all lockbox ios users
  app/scripts/lib/experiments/grouping-rules/token-code.js
  app/tests/spec/lib/experiments/grouping-rules/token-code.js
Labels: train-127, waffle:review

#6746 feat(sms): remove SMS padlock
  app/images/icon-secure-lock.svg
  app/scripts/templates/sms_send.mustache
  app/styles/modules/_branding.scss
Labels: waffle:active

#6744 fix(reset): remove confusing account recovery password reset messaging
  app/scripts/views/confirm_reset_password.js
  app/tests/spec/views/confirm_reset_password.js
Labels: waffle:active

#6747 chore(release): Merge train-127 into master
  CHANGELOG.md
  package.json
Labels: waffle:review

#6761 fix(nsp): add advistory 745
  .nsprc
Labels: waffle:active

#6762 fix(metrics): make sure to track oauth screen views in amplitude
  server/lib/amplitude.js
  tests/server/amplitude.js
Labels: waffle:active

#6768 fix(secondary-emails): Handle long emails in the secondary email panel
  app/scripts/templates/settings/emails.mustache
  app/styles/modules/_settings.scss
  app/tests/spec/views/settings/emails.js
Labels: waffle:review

#6766 chore(recovery-key): Remove all recovery key experiment code.
  app/scripts/lib/experiments/grouping-rules/index.js
  app/scripts/lib/experiments/grouping-rules/recovery-key.js
  app/scripts/models/auth_brokers/base.js
  app/scripts/views/mixins/recovery-key-experiment-mixin.js
  app/scripts/views/ready.js
  app/scripts/views/settings/account_recovery/account_recovery.js
  app/tests/spec/lib/experiments/grouping-rules/index.js
  app/tests/spec/lib/experiments/grouping-rules/recovery-key.js
  app/tests/spec/views/ready.js
  app/tests/spec/views/settings/account_recovery/account_recovery.js
  app/tests/test_start.js
  tests/functional/recovery_key.js
Labels: waffle:review

#6759 feat(npm): update to latest npmshrink
  npm-shrinkwrap.json
  package.json
  scripts/tls-shrink.sh
Labels: waffle:active

#6850 fix(styles): address the radius mismatch on the send button
  app/styles/_variables.scss
  app/styles/modules/_branding.scss
Labels: waffle:active

#6851 feat(metrics): add country and region to flow events
  server/lib/amplitude.js
  server/lib/flow-event.js
  tests/server/amplitude.js
  tests/server/flow-event.js
Labels: train-128, waffle:review
