Repository mozilla/fxa-content-server, pull requests merged in 2018-04, with the labels that each got.

#6020 feat(oauth): support Notes Android redirect
  server/lib/configuration.js
Labels: train-109, waffle:active

#6021 fix(metrics): add locale to flow events
  server/lib/flow-event.js
  tests/server/flow-event.js
Labels: waffle:active

#6019 chore(emails): use popular email domain list from fxa-shared
  app/scripts/lib/constants.js
  app/scripts/lib/popular-email-domains.json
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#6015 refactor(style): removing gravatar from csp rules
  server/lib/csp/blocking.js
  tests/server/csp.js
Labels: waffle:backlog

#6032 feat(sms): Partial SMS rollout in BE and NL.
  app/scripts/lib/country-telephone-info.js
Labels: train-110, waffle:review

#6022 refactor(metrics): use boiler-plate amplitude code from fxa-shared
  npm-shrinkwrap.json
  package.json
  server/lib/amplitude.js
  tests/server/amplitude.js
Labels: waffle:review

#6036 fix(experiment): Disable A/B experiment interface for navigator.webdr…
  app/scripts/lib/experiment.js
  app/tests/spec/lib/experiment.js
Labels: waffle:active

#6041 chore(docs): Remove obsolete oauth-in-an-iframe docs.
  docs/relier-communication-protocols/iframe.md
Labels: waffle:review

#6038 chore(deps): Update sinon to @4.5.0
  app/tests/spec/views/settings/communication_preferences.js
  npm-shrinkwrap.json
  package.json
  webpack.config.js
Labels: train-110, waffle:review

#6042 fix(npm): update to npm5
  npm-shrinkwrap.json
Labels: waffle:review

#6054 fix(test): Remove duplicate email_first functional test entries.
  tests/functional.js
Labels: waffle:review

#6055 chore(deps): Remove the babel-middleware dependency, it's not used.
  npm-shrinkwrap.json
  package.json
Labels: waffle:review

#6065 feat(SMS): Roll out Denmark(DK) to 50%.
  app/scripts/lib/country-telephone-info.js
Labels: train-110, waffle:review

#6048 fix(css): make qr code padding consistent
  app/styles/modules/_settings-totp.scss
Labels: waffle:review

#6064 fix(email): send correct email when using unblock code
  app/scripts/models/account.js
  app/tests/spec/models/account.js
  tests/functional/lib/selectors.js
  tests/functional/settings_change_email.js
Labels: waffle:review

#6066 fix(tests): enable TOTP tests on Circle
  tests/functional_circle.js
Labels: waffle:active

#6067 fix(email-first): Ensure "Mistyped email" links work as expected.
  app/scripts/lib/router.js
  app/scripts/views/index.js
  app/tests/spec/lib/router.js
  app/tests/spec/views/index.js
  tests/functional/fx_firstrun_v2_email_first.js
  tests/functional/lib/selectors.js
  tests/functional/sync_v3_email_first.js
Labels: train-110, waffle:review

#6069 fix(totp): Fix the "can add TOTP to account and confirm web signin" test
  app/scripts/templates/settings/two_step_authentication.mustache
Labels: waffle:review

#6034 feat(email-first): Enable the email-first flow for OAuth reliers.
  app/scripts/lib/router.js
  app/scripts/lib/vat.js
  app/scripts/models/reliers/oauth.js
  app/scripts/models/reliers/sync.js
  app/scripts/views/index.js
  app/scripts/views/oauth_index.js
  app/tests/spec/models/reliers/oauth.js
  app/tests/spec/views/index.js
  app/tests/spec/views/oauth_index.js
  tests/functional/oauth_email_first.js
  tests/functional_oauth.js
Labels: lockbox, train-111, waffle:review

#6075 fix(tests): update tests for recovery code updates
  app/scripts/lib/validate.js
  app/scripts/views/sign_in_recovery_code.js
  app/tests/spec/views/elements/recovery-code-input.js
  tests/functional/sign_in_recovery_code.js
Labels: shipit, train-110, waffle:review

#6062 feat(node): run travis with node 8
  .travis.yml
  server/lib/version.js
Labels: waffle:active

#6087 feat(metrics): Generate a node.js compatible experiment name list
  app/scripts/lib/experiments/grouping-rules/TEMPLATE.js
  app/scripts/lib/experiments/grouping-rules/base.js
  app/scripts/lib/experiments/grouping-rules/communication-prefs.js
  app/scripts/lib/experiments/grouping-rules/email-first.js
  app/scripts/lib/experiments/grouping-rules/index.js
  app/scripts/lib/experiments/grouping-rules/is-sampled-user.js
  app/scripts/lib/experiments/grouping-rules/q3-form-changes.js
  app/scripts/lib/experiments/grouping-rules/send-sms-install-link.js
  app/scripts/lib/experiments/grouping-rules/sentry.js
  app/scripts/lib/experiments/grouping-rules/sessions.js
  app/scripts/lib/experiments/grouping-rules/token-code.js
  app/tests/spec/lib/experiments/grouping-rules/index.js
  webpack.config.js
Labels: waffle:review

#6086 fix(server): fix undefined dereference
  server/lib/user-agent.js
Labels: waffle:active

#6088 feat(node): update to node 8
  .travis.yml
  Dockerfile-build
  package.json
Labels: waffle:active

#6103 fix(code): disable token code experiment for 123done
  app/scripts/lib/experiments/grouping-rules/token-code.js
  app/tests/spec/lib/experiments/grouping-rules/token-code.js
Labels: waffle:active

#6111 fix(permissions): Allow untrusted reliers to request 'openid' scope.
  app/scripts/lib/constants.js
  app/tests/spec/models/reliers/oauth.js
Labels: waffle:active

#6112 Uplift train-110 to master
  CHANGELOG.md
  app/scripts/lib/constants.js
  app/tests/spec/models/reliers/oauth.js
  package.json
Labels: waffle:active

#6117 fix(test): fix totp test failures
  tests/functional/lib/helpers.js
  tests/functional/oauth_sign_in.js
Labels: waffle:review

#6119 fix(ci): clean up travis logs
  .travis.yml
  tests/ci/deps.sh
Labels: waffle:active

#6110 fix(templates): match local behaviour of templates with prod
  tests/server/l10n.js
  tests/server/lang.js
Labels: waffle:active

#6121 fix(tests): fix OAuth permission test
  tests/functional/oauth_permissions.js
Labels: waffle:active

#6100 fix(css): Update recovery code placeholder text, and recovery code css size
  app/images/recovery_code_copy.svg
  app/images/recovery_code_download.svg
  app/images/recovery_code_print.svg
  app/images/recovery_code_replace.svg
  app/scripts/templates/sign_in_recovery_code.mustache
  app/styles/modules/_settings-totp.scss
Labels: train-111, waffle:review

#6044 fix(metrics): stop using user-agent string in flow id check
  server/lib/flow-metrics.js
  tests/server/flow-metrics.js
Labels: waffle:active

#6130 refactor(sync): Remove support for migration=sync11
  app/scripts/lib/constants.js
  app/scripts/models/reliers/relier.js
  app/scripts/models/reliers/sync.js
  app/scripts/templates/sign_in.mustache
  app/scripts/templates/sign_up.mustache
  app/scripts/views/mixins/migration-mixin.js
  app/scripts/views/sign_in.js
  app/scripts/views/sign_up.js
  app/tests/spec/lib/metrics.js
  app/tests/spec/lib/storage-metrics.js
  app/tests/spec/models/reliers/relier.js
  app/tests/spec/models/reliers/sync.js
  app/tests/spec/views/mixins/migration-mixin.js
  app/tests/spec/views/mixins/sync-suggestion-mixin.js
  app/tests/spec/views/sign_in.js
  app/tests/spec/views/sign_up.js
  tests/functional/sync_sign_in.js
  tests/functional/sync_sign_up.js
  tests/server/flow-event.js
  tests/server/metrics-collector-stderr.js
Labels: waffle:active

#5922 feat(session): update upgrade session panel
  app/scripts/lib/channels/notifier.js
  app/scripts/lib/fxa-client.js
  app/scripts/models/account.js
  app/scripts/models/auth_brokers/base.js
  app/scripts/models/reliers/relier.js
  app/scripts/templates/settings/upgrade_session.mustache
  app/scripts/views/behaviors/settings.js
  app/scripts/views/mixins/session-verified-notification-mixin.js
  app/scripts/views/mixins/upgrade-session-mixin.js
  app/scripts/views/settings/emails.js
  app/scripts/views/settings/two_step_authentication.js
  app/styles/modules/_settings-totp.scss
  app/tests/spec/views/behaviors/settings.js
  app/tests/spec/views/mixins/session-verified-notification-mixin.js
  app/tests/spec/views/settings/two_step_authentication.js
  app/tests/test_start.js
  tests/functional/lib/selectors.js
  tests/functional/settings_secondary_emails.js
  tests/functional/sign_in_totp.js
Labels: train-111, waffle:review

#6134 fix(tests): teamcity server tests now need underscore and js-md5
  tests/teamcity/install-npm-deps.sh
Labels: waffle:active

#6131 refactor(oauth): Remove support for migration=amo
  app/scripts/models/reliers/relier.js
  app/scripts/templates/sign_in.mustache
  app/scripts/templates/sign_up.mustache
  app/scripts/views/mixins/migration-mixin.js
  app/scripts/views/sign_in.js
  app/scripts/views/sign_up.js
  app/tests/spec/lib/metrics.js
  app/tests/spec/models/reliers/relier.js
  app/tests/spec/views/mixins/migration-mixin.js
  app/tests/spec/views/oauth_sign_in.js
  app/tests/spec/views/sign_in.js
  app/tests/spec/views/sign_up.js
  app/tests/test_start.js
  tests/functional/amo_sign_up.js
  tests/functional_oauth.js
Labels: train-111, waffle:review

#6017 feat(keys): Allow fetching scoped keys for use with Firefox Sync.
  app/scripts/lib/app-start.js
  app/scripts/lib/oauth-errors.js
  app/scripts/models/auth_brokers/oauth.js
  app/scripts/models/reliers/oauth.js
  app/tests/spec/lib/app-start.js
  app/tests/spec/lib/crypto/scoped-keys.js
  app/tests/spec/models/auth_brokers/oauth.js
  app/tests/spec/models/reliers/oauth.js
  npm-shrinkwrap.json
  package.json
  server/lib/configuration.js
Labels: shipit, train-111, waffle:review
