Repository mozilla/fxa-content-server, pull requests merged in 2018-08, with the labels that each got.

#6407 feat(recovery): add account recovery experiment
  app/scripts/lib/experiments/grouping-rules/index.js
  app/scripts/lib/experiments/grouping-rules/recovery-key.js
  app/scripts/views/mixins/recovery-key-experiment-mixin.js
  app/tests/spec/lib/experiments/grouping-rules/index.js
  app/tests/spec/lib/experiments/grouping-rules/recovery-key.js
  app/tests/test_start.js
Labels: WIP, train-118, waffle:active

#6392 feat(recovery): account recovery phase 1.5 setup screens
  app/images/recovery_key_download.svg
  app/images/recovery_key_print.svg
  app/scripts/lib/constants.js
  app/scripts/lib/fxa-client.js
  app/scripts/lib/router.js
  app/scripts/models/account.js
  app/scripts/models/auth_brokers/base.js
  app/scripts/templates/settings/account_recovery/account_recovery.mustache
  app/scripts/templates/settings/account_recovery/confirm_password.mustache
  app/scripts/templates/settings/account_recovery/confirm_revoke.mustache
  app/scripts/templates/settings/account_recovery/recovery_key.mustache
  app/scripts/templates/settings/account_recovery/recovery_key_print.mustache
  app/scripts/templates/settings/two_step_authentication.mustache
  app/scripts/views/mixins/modal-settings-panel-mixin.js
  app/scripts/views/settings.js
  app/scripts/views/settings/account_recovery/account_recovery.js
  app/scripts/views/settings/account_recovery/confirm_password.js
  app/scripts/views/settings/account_recovery/confirm_revoke.js
  app/scripts/views/settings/account_recovery/recovery_key.js
  app/styles/_modules.scss
  app/styles/_variables.scss
  app/styles/modules/_settings-account-recovery.scss
  app/styles/modules/_settings-totp.scss
  app/styles/modules/_settings.scss
  app/tests/spec/views/settings/account_recovery/account_recovery.js
  app/tests/spec/views/settings/account_recovery/confirm_password.js
  app/tests/spec/views/settings/account_recovery/confirm_revoke.js
  app/tests/spec/views/settings/account_recovery/recovery_key.js
  app/tests/test_start.js
  npm-shrinkwrap.json
  package.json
  server/lib/routes/get-frontend.js
  tests/functional.js
  tests/functional/lib/selectors.js
  tests/functional/recovery_key.js
  tests/functional_circle.js
Labels: waffle:review

#6410 feat(tests): migrate to circle 2
  .circleci/config.yml
  circle.yml
  tests/functional/sign_in_totp.js
Labels: waffle:active

#6415 fix(tests): update test timeout
  tests/functional/lib/helpers.js
Labels: waffle:active

#6412 chore(test): Re-enable link checks in Fx TOS/PP
  tests/server/helpers/routesHelpers.js
Labels: waffle:active

#6416 fix(codes): center align totp back links
  app/scripts/templates/sign_in_recovery_code.mustache
  app/scripts/templates/sign_in_totp_code.mustache
Labels: train-118, waffle:review

#6419 fix(tests): update token code experiment tests
  tests/functional/sync_v3_sign_in.js
Labels: shipit, train-118, waffle:review

#6421 fix(links): add account recovery sumo link
  app/scripts/views/settings/account_recovery/account_recovery.js
  app/tests/spec/views/settings/account_recovery/account_recovery.js
Labels: train-118, waffle:active

#6423 chore(release): Merge train-118 into master
  CHANGELOG.md
  package.json
Labels: waffle:active

#6424 fix(ci): build on tags
  .circleci/config.yml
Labels: waffle:active

#6425 Release v1.118.1
  CHANGELOG.md
  package.json
Labels: waffle:active

#6426 fix(scripts): update `npm run-script start-circle`
  package.json
Labels: waffle:active

#6432 fix(test): Fix the handshake test.
  tests/functional/fx_desktop_handshake.js
Labels: waffle:review

#6437 chore(release): Merge v1.118.1 tag into train-118
  .circleci/config.yml
  CHANGELOG.md
  package.json
Labels: waffle:active

#6418 fix(recovery): account recovery updates from ux review
  app/images/recovery_key_key.svg
  app/scripts/templates/settings/account_recovery/account_recovery.mustache
  app/scripts/templates/settings/account_recovery/confirm_password.mustache
  app/scripts/templates/settings/account_recovery/recovery_key.mustache
  app/scripts/views/settings.js
  app/styles/modules/_settings-account-recovery.scss
  tests/functional/lib/selectors.js
  tests/functional/recovery_key.js
Labels: waffle:review

#6443 chore(deps): Remove coveralls
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#6444 chore(deps): Remove grunt-contrib-watch
  grunttasks/watch.js
  npm-shrinkwrap.json
  package.json
  server/templates/pages/src/mocha.html
Labels: waffle:active

#6447 feat(password-strength): Bump experiment to 100% in en, 20% in de
  app/scripts/lib/experiments/grouping-rules/password-strength.js
  app/tests/spec/lib/experiments/grouping-rules/password-strength.js
Labels: waffle:active

#6442 fix(email-first): Show password works in email-first
  app/scripts/views/sign_in_password.js
  app/scripts/views/sign_up_password.js
  tests/functional/fx_firstrun_v2_email_first.js
  tests/functional/lib/selectors.js
  tests/functional/oauth_email_first.js
  tests/functional/sync_v3_email_first.js
Labels: train-118, waffle:review

#6450 chore(release): Release v1.118.2
  CHANGELOG.md
  package.json
Labels: waffle:active

#6433 fix(css): Maximized visible password area
  app/styles/modules/_password-row.scss
Labels: waffle:active

#6455 fix(test): Run all the unit tests!
  app/tests/spec/lib/experiments/grouping-rules/password-strength.js
Labels: waffle:review

#6456 chore(release): Merge train-118 into master
  app/tests/spec/lib/experiments/grouping-rules/password-strength.js
Labels: waffle:active

#6449 fix(tests): fix broken token code oauth tests
  tests/functional/sign_in_token_code.js
Labels: waffle:review

#6460 fix(oauth): Show an error message when clicking "continue" errors.
  app/scripts/views/ready.js
  app/tests/spec/views/ready.js
Labels: waffle:active

#6431 feat(recovery): add recovery key metrics
  app/scripts/lib/router.js
  app/scripts/lib/verification-reasons.js
  app/scripts/views/account_recovery_confirm_key.js
  app/scripts/views/complete_reset_password.js
  app/scripts/views/ready.js
  app/scripts/views/settings/account_recovery/account_recovery.js
  app/scripts/views/settings/account_recovery/confirm_password.js
  app/scripts/views/settings/account_recovery/confirm_revoke.js
  app/scripts/views/settings/account_recovery/recovery_key.js
  app/tests/spec/views/account_recovery_confirm_key.js
  app/tests/spec/views/settings/account_recovery/account_recovery.js
  app/tests/spec/views/settings/account_recovery/confirm_password.js
  app/tests/spec/views/settings/account_recovery/confirm_revoke.js
  server/lib/routes/get-frontend.js
Labels: train-119, waffle:review

#6462 fix(metrics): stop sending unused performance flow events
  server/lib/flow-event.js
  tests/server/flow-event.js
Labels: train-119, waffle:review

#6453 chore(modules): Convert account.js & tests to use ES6 modules
  app/scripts/models/account.js
  app/tests/spec/models/account.js
Labels: waffle:review

#6461 fix(recovery): use `enable` instead of `add` button
  app/scripts/templates/settings/account_recovery/account_recovery.mustache
Labels: train-119:qa-needed, waffle:review

#6466 chore(release): Merge train-119 into master
  CHANGELOG.md
  package.json
Labels: waffle:active

#6465 feat(tests): assert that validation regexes match docs
  npm-shrinkwrap.json
  package.json
  tests/server/validation.js
  tests/tests_server.js
Labels: waffle:review

#6471 Uplift train-119 into master
  CHANGELOG.md
  package.json
  server/lib/routes/get-metrics-flow.js
  tests/server/routes/get-metrics-flow.js
Labels: waffle:review

#6420 fix(deps): Update deps, remove nsp, add `npm audit` logging in travis
  .nsprc
  .travis.yml
  grunttasks/nsp.js
  npm-shrinkwrap.json
  package.json
Labels: train-120, waffle:review

#6468 Enable recovery key experiment for test emails
  app/scripts/views/mixins/recovery-key-experiment-mixin.js
  app/scripts/views/settings/account_recovery/account_recovery.js
  app/tests/spec/views/settings/account_recovery/account_recovery.js
  tests/functional/lib/helpers.js
  tests/functional/recovery_key.js
Labels: train-119, train-119:qa-needed, waffle:review

#6475 fix(deps): Update several deps to their latest.
  grunttasks/csslint.js
  grunttasks/htmllint.js
  npm-shrinkwrap.json
  package.json
  server/templates/pages/src/index.html
  tests/tools/firefox_profile_creator.js
Labels: waffle:review

#6477 feat(pw-strength): designF is rolled out to 100% of english users.
  app/scripts/lib/experiments/grouping-rules/password-strength.js
  app/tests/spec/lib/experiments/grouping-rules/password-strength.js
Labels: train-119, waffle:review

#6481 Train 119 uplift
  CHANGELOG.md
  app/scripts/lib/experiments/grouping-rules/password-strength.js
  app/scripts/views/mixins/recovery-key-experiment-mixin.js
  app/scripts/views/settings/account_recovery/account_recovery.js
  app/tests/spec/lib/experiments/grouping-rules/password-strength.js
  app/tests/spec/views/settings/account_recovery/account_recovery.js
  package.json
  tests/functional/lib/helpers.js
  tests/functional/recovery_key.js
Labels: waffle:active

#6479 refactor(modules): Convert a bunch of modules to ES6 format
  app/scripts/lib/search-param-mixin.js
  app/scripts/lib/url.js
  app/scripts/lib/user-agent.js
  app/scripts/models/mixins/search-param.js
  app/scripts/models/reliers/relier.js
  app/scripts/models/reliers/sync.js
  app/tests/spec/lib/search-param-mixin.js
  app/tests/spec/lib/url.js
  app/tests/spec/lib/user-agent.js
  app/tests/spec/models/mixins/search-param.js
  app/tests/spec/models/reliers/relier.js
  app/tests/spec/models/reliers/sync.js
Labels: waffle:active

#6470 feat(tests): add E2E tests for the fxa-email-service
  tests/functional.js
  tests/functional/email_service.js
  tests/functional_circle.js
Labels: waffle:active

#6485 fix(tests): install request and request-promise in TeamCity
  tests/teamcity/install-npm-deps.sh
Labels: waffle:active

#6483 feat(errors): improve metrics and style of the Working error
  app/scripts/views/base.js
  app/styles/_state.scss
  app/tests/spec/views/base.js
Labels: waffle:active

#6501 chore(modules): Convert a couple of modules to ES6 format.
  app/scripts/lib/crypto/scoped-keys.js
  app/scripts/models/auth_brokers/index.js
  app/tests/spec/lib/crypto/scoped-keys.js
  app/tests/spec/models/auth_brokers/index.js
Labels: waffle:review

#6502 feat(mixins): Add hash parameter processing for the pairing flow.
  app/scripts/lib/channels/web.js
  app/scripts/lib/url-mixin.js
  app/scripts/lib/url.js
  app/scripts/lib/user-agent-mixin.js
  app/scripts/models/auth_brokers/base.js
  app/scripts/models/flow.js
  app/scripts/models/mixins/search-param.js
  app/scripts/models/mixins/url.js
  app/scripts/models/reliers/relier.js
  app/scripts/models/sync-engines.js
  app/scripts/models/unique-user-id.js
  app/scripts/models/user.js
  app/scripts/views/base.js
  app/tests/spec/lib/url-mixin.js
  app/tests/spec/lib/url.js
  app/tests/spec/models/mixins/search-param.js
  app/tests/spec/models/mixins/url.js
  app/tests/test_start.js
Labels: waffle:review

#6503 feat(ua-parser): Add a `genericDeviceType` method.
  app/scripts/lib/user-agent.js
  app/tests/spec/lib/user-agent.js
Labels: waffle:review

#6508 fix(tests): return promise so on error it's not unhandled rejection
  tests/server/helpers/routesHelpers.js
Labels: waffle:active

#6482 fix(codes): redirect user to replace recovery codes when they are low
  app/scripts/views/mixins/modal-settings-panel-mixin.js
  app/scripts/views/sign_in_recovery_code.js
  app/tests/spec/views/sign_in_recovery_code.js
  tests/functional/lib/selectors.js
  tests/functional/sign_in_recovery_code.js
Labels: waffle:review

#6509 fix(style): don't display firefox logo on small screens for CWTS
  app/styles/modules/_branding.scss
Labels: train-120, waffle:active

#6510 fix(tests): auto-download nightly, and config to run tests with nightly
  tests/teamcity/latest-nightly
  tests/teamcity/stage-nightly
  tests/teamcity/update-builds.sh
Labels: waffle:active
