Repository mozilla/fxa-content-server, pull requests merged in 2018-05, with the labels that each got.

#6140 fix(npm): update to shrinkwrap with dev
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#6143 fix(docker): Force npm@5 in docker builds.
  Dockerfile-build
  server/bin/fxa-content-server.js
  server/lib/user-agent.js
  tests/server/user-agent.js
Labels: train-110, waffle:review

#6099 fix(session): add session token to account delete
  app/scripts/lib/fxa-client.js
  app/scripts/models/account.js
  npm-shrinkwrap.json
  package.json
  tests/functional/lib/selectors.js
  tests/functional/sign_in_totp.js
Labels: shipit, train-111, waffle:review

#6148 fix(strings): remove extra spaces from session
  app/scripts/templates/settings/upgrade_session.mustache
Labels: waffle:active

#6150 Release v1.111.0
  AUTHORS
  CHANGELOG.md
  package.json
Labels: waffle:active

#6141 feat(totp): add experiment logic for TOTP
  app/scripts/lib/experiments/grouping-rules/index.js
  app/scripts/lib/experiments/grouping-rules/totp.js
  app/scripts/views/mixins/totp-experiment-mixin.js
  app/scripts/views/settings/two_step_authentication.js
  app/tests/spec/lib/experiments/grouping-rules/index.js
  app/tests/spec/lib/experiments/grouping-rules/totp.js
  app/tests/spec/views/settings/two_step_authentication.js
  app/tests/test_start.js
Labels: train-111, waffle:review

#6146 feat(style): Use system fonts instead of Fira Sans
  .gitignore
  app/styles/_system-font-mixins.scss
  app/styles/_variables.scss
  app/styles/system-font-main.scss
  grunttasks/build.js
  grunttasks/clean.js
  grunttasks/concurrent.js
  grunttasks/connect-fonts.js
  grunttasks/css.js
  grunttasks/l10n-generate-pages.js
  grunttasks/sass.js
  grunttasks/server.js
  npm-shrinkwrap.json
  package.json
  server/lib/configuration.js
  server/lib/i18n.js
  server/templates/pages/src/404.html
  server/templates/pages/src/500.html
  server/templates/pages/src/502.html
  server/templates/pages/src/503.html
  server/templates/pages/src/index.html
  server/templates/pages/src/privacy.html
  server/templates/pages/src/style-guide.html
  server/templates/pages/src/terms.html
  tests/functional.js
  tests/functional/fonts.js
  tests/server/helpers/routesHelpers.js
  tests/server/l10n.js
Labels: train-112, waffle:review

#6159 fix(totp): add sumo link for totp
  app/scripts/templates/settings/two_step_authentication.mustache
  app/scripts/views/settings/two_step_authentication.js
  app/tests/spec/views/settings/two_step_authentication.js
Labels: waffle:active

#6160 fix(basket): Match the expected basket subscribe & lookup-user API
  app/scripts/lib/marketing-email-client.js
  app/scripts/lib/xhr.js
  app/scripts/models/marketing-email-prefs.js
  app/tests/spec/lib/marketing-email-client.js
  app/tests/spec/lib/xhr.js
  app/tests/spec/models/marketing-email-prefs.js
Labels: train-112, waffle:review

#6163 fix(metrics): remove temporary flow validation fallback code
  server/lib/flow-event.js
  server/lib/flow-metrics.js
  tests/server/flow-metrics.js
Labels: waffle:review

#6153 fix(totp): send service name when verifing totp token
  app/scripts/lib/fxa-client.js
  app/scripts/models/account.js
  app/scripts/views/settings/two_step_authentication.js
  app/scripts/views/sign_in_totp_code.js
  app/tests/spec/lib/fxa-client.js
  app/tests/spec/models/account.js
  app/tests/spec/views/settings/two_step_authentication.js
Labels: train-112, waffle:review

#6155 feat(style): Apply Photon styles to the buttons
  app/scripts/templates/complete_reset_password.mustache
  app/scripts/templates/confirm.mustache
  app/scripts/templates/pp.mustache
  app/scripts/templates/reset_password.mustache
  app/scripts/templates/settings.mustache
  app/scripts/templates/settings/avatar.mustache
  app/scripts/templates/settings/avatar_camera.mustache
  app/scripts/templates/settings/avatar_change.mustache
  app/scripts/templates/settings/avatar_crop.mustache
  app/scripts/templates/settings/change_password.mustache
  app/scripts/templates/settings/client_disconnect.mustache
  app/scripts/templates/settings/clients.mustache
  app/scripts/templates/settings/communication_preferences.mustache
  app/scripts/templates/settings/delete_account.mustache
  app/scripts/templates/settings/display_name.mustache
  app/scripts/templates/settings/emails.mustache
  app/scripts/templates/settings/recovery_codes.mustache
  app/scripts/templates/settings/two_step_authentication.mustache
  app/scripts/templates/settings/upgrade_session.mustache
  app/scripts/templates/sms_send.mustache
  app/scripts/templates/test_template.mustache
  app/scripts/templates/tos.mustache
  app/scripts/views/settings/emails.js
  app/styles/_base.scss
  app/styles/_variables.scss
  app/styles/modules/_branding.scss
  app/styles/modules/_button-row.scss
  app/styles/modules/_password-row.scss
  app/styles/modules/_settings.scss
  app/styles/modules/_tooltip.scss
  app/tests/spec/views/mixins/disable-form-mixin.js
  app/tests/spec/views/settings/avatar.js
  app/tests/spec/views/settings/display_name.js
  app/tests/spec/views/settings/emails.js
  server/templates/pages/src/404.html
  server/templates/pages/src/500.html
  server/templates/pages/src/502.html
  server/templates/pages/src/503.html
  tests/functional/avatar.js
  tests/functional/lib/selectors.js
  tests/functional/settings_clients.js
Labels: train-112, waffle:review

#6164 refactor(experiment): Remove the q3FormChanges experiment.
  app/scripts/lib/experiment.js
  app/scripts/lib/experiments/grouping-rules/base.js
  app/scripts/lib/experiments/grouping-rules/email-first.js
  app/scripts/lib/experiments/grouping-rules/q3-form-changes.js
  app/tests/spec/lib/experiments/grouping-rules/base.js
  app/tests/spec/lib/experiments/grouping-rules/email-first.js
  app/tests/spec/lib/experiments/grouping-rules/q3-form-changes.js
Labels: train-112, waffle:active

#6167 refactor(style): Update anchors to use photon colors.
  app/styles/_base.scss
  app/styles/_mixins.scss
  app/styles/_state.scss
  app/styles/_variables.scss
  app/styles/modules/_branding.scss
  app/styles/modules/_cropper.scss
  app/styles/modules/_custom-rows.scss
  app/styles/modules/_legal.scss
  app/styles/modules/_marketing-ios.scss
  app/styles/modules/_settings.scss
  app/styles/modules/_tooltip.scss
Labels: train-112, waffle:review

#6179 fix(nsp): update devs and nsp
  .nsprc
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#6178 fix(client): improve messaging before delete account
  app/scripts/templates/settings/delete_account.mustache
Labels: waffle:review

#6175 refactor(styles): Apply Photon styles to input fields.
  app/scripts/templates/complete_reset_password.mustache
  app/scripts/templates/partial/coppa-age-input.mustache
  app/scripts/templates/settings/change_password.mustache
  app/scripts/templates/settings/delete_account.mustache
  app/scripts/templates/settings/display_name.mustache
  app/scripts/templates/settings/emails.mustache
  app/scripts/templates/settings/two_step_authentication.mustache
  app/scripts/templates/sign_up.mustache
  app/scripts/templates/sign_up_password.mustache
  app/scripts/templates/test_template.mustache
  app/scripts/views/complete_reset_password.js
  app/scripts/views/mixins/coppa-mixin.js
  app/scripts/views/mixins/floating-placeholder-mixin.js
  app/scripts/views/mixins/settings-panel-mixin.js
  app/scripts/views/settings/change_password.js
  app/scripts/views/settings/client_disconnect.js
  app/scripts/views/settings/delete_account.js
  app/scripts/views/settings/display_name.js
  app/scripts/views/settings/emails.js
  app/scripts/views/settings/two_step_authentication.js
  app/scripts/views/sign_up.js
  app/styles/_base.scss
  app/styles/_mixins.scss
  app/styles/_variables.scss
  app/styles/modules/_branding.scss
  app/styles/modules/_custom-rows.scss
  app/styles/modules/_input-row.scss
  app/styles/modules/_password-row.scss
  app/styles/modules/_select-row.scss
  app/styles/modules/_settings.scss
  app/tests/spec/views/mixins/floating-placeholder-mixin.js
  app/tests/spec/views/mixins/settings-panel-mixin.js
  app/tests/spec/views/settings/delete_account.js
  app/tests/spec/views/settings/display_name.js
  app/tests/test_start.js
Labels: waffle:active

#6177 revert(csp): revert removing csp support for gravatar
  server/lib/csp/blocking.js
  tests/server/csp.js
Labels: waffle:review

#6183 refactor(style): Apply Photon styles to message boxes
  app/images/icon-close.svg
  app/scripts/templates/connect_another_device.mustache
  app/scripts/templates/partial/sync-suggestion.mustache
  app/scripts/templates/settings/recovery_codes.mustache
  app/scripts/templates/sign_up.mustache
  app/styles/_mixins.scss
  app/styles/_state.scss
  app/styles/_variables.scss
  app/styles/modules/_modal.scss
  app/styles/modules/_settings.scss
  tests/functional/lib/selectors.js
  tests/functional/sign_in_totp.js
Labels: waffle:review

#6184 fix(show-password): replace show password with icon
  app/images/icon-show-password.svg
  app/scripts/templates/partial/show-password.mustache
  app/styles/_mixins.scss
  app/styles/_variables.scss
  app/styles/modules/_password-row.scss
Labels: train-112, waffle:review

#6181 feat(recovery): update view when low on recovery codes
  app/scripts/templates/settings/recovery_codes.mustache
  app/scripts/views/settings/recovery_codes.js
  app/styles/modules/_settings-totp.scss
  app/tests/spec/views/settings/recovery_codes.js
  tests/functional/lib/selectors.js
  tests/functional/sign_in_totp.js
Labels: train-112, waffle:review

#6190 feat(sms): Fully roll out SMS in BE, DK, NL
  app/scripts/lib/country-telephone-info.js
Labels: train-112, waffle:active

#6194 fix(test): Fix tests due to an obscured "Sign out" button.
  tests/functional/lib/helpers.js
  tests/functional/sign_in_totp.js
Labels: train-112, waffle:review

#6192 fix(settings): Fix the position of the rotate button.
  app/scripts/templates/settings/avatar_crop.mustache
  app/styles/_mixins.scss
  app/styles/modules/_cropper.scss
  app/styles/modules/_settings-totp.scss
Labels: train-112, waffle:review

#6187 feat(signin): Show a user "card" for the email-first signin flow.
  app/scripts/templates/partial/user-card.mustache
  app/scripts/templates/sign_in_password.mustache
  app/scripts/views/index.js
  app/scripts/views/mixins/user-card-mixin.js
  app/scripts/views/sign_in_password.js
  app/styles/_base.scss
  app/styles/modules/_avatar.scss
  app/tests/spec/views/index.js
  app/tests/spec/views/mixins/user-card-mixin.js
  app/tests/test_start.js
Labels: train-112, waffle:review

#6195 fix(tooltip): Show tooltips above the input on mobile
  app/scripts/views/tooltip.js
  app/styles/modules/_tooltip.scss
  app/tests/mocks/window.js
  app/tests/spec/views/tooltip.js
Labels: train-112, waffle:review

#6208 fix(config): Allow configuring statsd host
  .nsprc
  server/lib/configuration.js
Labels: waffle:active

#6211 fix(deps): Update fxa-geodb
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#6202 refactor(metrics): move amplitude email types back here from fxa-shared
  npm-shrinkwrap.json
  package.json
  server/lib/amplitude.js
Labels: waffle:active

#6212 feat(totp): enable totp for 10% of all users
  app/scripts/lib/experiments/grouping-rules/totp.js
Labels: train-112, waffle:active

#6216 fix(style): Fix the error message/heading styles in settings
  app/styles/modules/_settings.scss
Labels: train-112, waffle:review

#6215 fix(style): Fix the link focusring style.
  app/scripts/templates/confirm_reset_password.mustache
  app/scripts/templates/cookies_disabled.mustache
  app/styles/_base.scss
  app/styles/_mixins.scss
  app/styles/modules/_custom-rows.scss
Labels: train-112, waffle:active

#6200 fix(validation): Stricter utm_ parameter metrics validation
  server/lib/validation.js
  tests/server/metrics.js
  tests/server/routes/get-verify-email.js
Labels: train-113, waffle:active

#6233 fix(css): make sign-in confirm button blue
  app/scripts/templates/ready.mustache
Labels: train-113, waffle:review

#6227 feat(metrics): metrics flow for iframeless flow
  app/scripts/lib/metrics.js
  app/scripts/models/flow.js
  app/tests/spec/lib/metrics.js
  app/tests/spec/models/flow.js
  server/bin/fxa-content-server.js
  server/config/local.json-dist
  server/lib/configuration.js
  server/lib/flow-event.js
  server/lib/routes.js
  server/lib/routes/get-metrics-flow.js
  server/lib/routes/post-metrics.js
  tests/server/flow-event.js
  tests/server/routes/get-metrics-flow.js
  tests/server/routes/post-metrics.js
  tests/tests_server.js
Labels: shipit, train-113, waffle:active

#6214 Host oauth authorization URL on content server
  app/scripts/lib/router.js
  app/scripts/lib/vat.js
  app/scripts/models/reliers/oauth.js
  app/scripts/views/authorization.js
  app/tests/spec/models/reliers/oauth.js
  app/tests/spec/views/authorization.js
  app/tests/test_start.js
  server/lib/routes/get-frontend.js
  server/lib/routes/get-openid-configuration.js
  tests/functional/oauth_query_param_validation.js
  tests/functional/pages.js
  tests/server/routes.js
Labels: shipit, train-113, waffle:active
