Repository mozilla/fxa-content-server, pull requests merged in 2018-11, with the labels that each got.

#6689 fix(deps): Update fxa-geodb to get rid of the audit warning
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#6686 refactor(mobile): Remove support for mob_ios_v1 and mob_android_v1
  app/scripts/lib/constants.js
  app/scripts/models/auth_brokers/index.js
  app/scripts/models/auth_brokers/mob-android-v1.js
  app/scripts/models/auth_brokers/mob-ios-v1.js
  app/tests/spec/models/auth_brokers/index.js
  app/tests/spec/models/auth_brokers/mob-android-v1.js
  app/tests/spec/models/auth_brokers/mob-ios-v1.js
  app/tests/test_start.js
  docs/query-params.md
  tests/functional.js
  tests/functional/mob_android_v1.js
  tests/functional/mob_ios_v1.js
  tests/functional_circle.js
Labels: waffle:active

#6692 fix(metrics): generate an amplitude deviceId in GET /metrics-flow
  server/lib/routes/get-metrics-flow.js
  tests/server/routes/get-metrics-flow.js
  tests/tests_server.js
Labels: train-125, waffle:review

#6694 fix(tests): reinstate accidentally-disabled server tests
  tests/tests_server.js
Labels: train-125, waffle:review

#6697 chore(config): Add reference-browser to allowlist for oldsync scope.
  server/lib/configuration.js
Labels: waffle:review

#6701 chore(deps): update deps
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#6704 fix(recovery): remove recovery key control group
  app/scripts/lib/experiments/grouping-rules/recovery-key.js
  app/tests/spec/lib/experiments/grouping-rules/recovery-key.js
Labels: train-125, waffle:review

#6707 chore(modules): Convert the complete_reset_password code to ES6 modules
  app/scripts/views/complete_reset_password.js
  app/tests/spec/views/complete_reset_password.js
Labels: waffle:active

#6708 Release v1.125.0
  CHANGELOG.md
  package.json
Labels: waffle:active

#6695 fix(styles): fix icon for Firefox Add-ons
  app/styles/modules/_settings.scss
Labels: waffle:active

#6712 fix(tests): install node-uuid when running tests/teamcity/run-server.sh
  tests/teamcity/install-npm-deps.sh
Labels: waffle:active

#6715 refactor(headers): remove HPKP
  server/bin/fxa-content-server.js
  server/lib/configuration.js
  server/lib/hpkp.js
  tests/server/hpkp.js
  tests/tests_server.js
Labels: waffle:active

#6700 feat(signin): add use different account option in security/recovery codes
  app/scripts/templates/sign_in_recovery_code.mustache
  app/scripts/templates/sign_in_totp_code.mustache
  app/tests/spec/views/sign_in_recovery_code.js
  app/tests/spec/views/sign_in_totp_code.js
Labels: train-126, waffle:active

#6703 fix(reset): remove confusing password reset messaging
  app/scripts/views/confirm_reset_password.js
  app/tests/spec/views/confirm_reset_password.js
Labels: train-126, waffle:review

#6706 feat(pw-strength): Add pw-strength meter to password reset
  app/scripts/templates/complete_reset_password.mustache
  app/scripts/views/complete_reset_password.js
  app/scripts/views/mixins/password-strength-mixin.js
  app/tests/spec/views/complete_reset_password.js
  app/tests/spec/views/mixins/password-strength-mixin.js
  tests/functional/lib/selectors.js
  tests/functional/oauth_reset_password.js
  tests/functional/settings_change_email.js
  tests/functional/sync_reset_password.js
  tests/functional/sync_v2_reset_password.js
  tests/functional/sync_v3_reset_password.js
Labels: train-126, waffle:review

#6718 fix(validation): accept emails containing an apostrophe on the front-end
  app/scripts/lib/validate.js
  app/tests/spec/lib/validate.js
Labels: train-126, waffle:review

#6721 chore(config): Add the new Send redirect_uris to the Send scopedKeys list.
  server/lib/configuration.js
Labels: waffle:active

#6720 chore(oauth): Add tests for signing into an OAuth relier w/ a Sync sessionToken.
  tests/functional/lib/helpers.js
  tests/functional/oauth_sign_in.js
  tests/functional/settings.js
  tests/functional/sign_in_cached.js
Labels: waffle:review

#6727 fix(test): Fix the OAuth email-first functional test that used a common password.
  tests/functional/oauth_email_first.js
Labels: train-126, waffle:review

#6726 fix(l10n): Use an inline `t` function to ensure l10n works as expected.
  app/scripts/lib/auth-errors.js
  app/scripts/lib/channel-server-client-errors.js
  app/scripts/lib/mailcheck.js
  app/scripts/lib/marketing-email-errors.js
  app/scripts/lib/oauth-errors.js
  app/scripts/lib/profile-errors.js
  app/scripts/lib/strings.js
  app/scripts/models/auth_brokers/base.js
  app/scripts/models/auth_brokers/web.js
  app/scripts/models/reliers/sync.js
  app/scripts/views/base.js
  app/scripts/views/behaviors/settings.js
  app/scripts/views/confirm_reset_password.js
  app/scripts/views/force_auth.js
  app/scripts/views/mixins/account-reset-mixin.js
  app/scripts/views/mixins/last-checked-time-mixin.js
  app/scripts/views/mixins/open-webmail-mixin.js
  app/scripts/views/mixins/resend-mixin.js
  app/scripts/views/mixins/save-options-mixin.js
  app/scripts/views/mixins/signin-mixin.js
  app/scripts/views/mixins/upgrade-session-mixin.js
  app/scripts/views/permissions.js
  app/scripts/views/reset_password.js
  app/scripts/views/settings/account_recovery/account_recovery.js
  app/scripts/views/settings/account_recovery/recovery_key.js
  app/scripts/views/settings/change_password.js
  app/scripts/views/settings/client_disconnect.js
  app/scripts/views/settings/clients.js
  app/scripts/views/settings/communication_preferences.js
  app/scripts/views/settings/delete_account.js
  app/scripts/views/settings/display_name.js
  app/scripts/views/settings/emails.js
  app/scripts/views/settings/recovery_codes.js
  app/scripts/views/settings/two_step_authentication.js
  app/scripts/views/sign_in.js
  app/scripts/views/sign_up.js
Labels: shipit, train-126, waffle:review

#6729 chore(config): Add the new Send redirect_uris to the Send scopedKeys list.
  server/lib/configuration.js
Labels: waffle:active

#6732 chore(release): Merge train-126 into master
  AUTHORS
  CHANGELOG.md
  package.json
Labels: waffle:active
