Repository mozilla/fxa-content-server, pull requests merged in 2018-03, with the labels that each got.

#5942 feat(avatars): support new default avatar API
  app/scripts/models/account.js
  app/scripts/models/profile-image.js
  app/scripts/templates/settings/avatar.mustache
  app/scripts/views/settings/avatar.js
  app/tests/spec/models/account.js
  app/tests/spec/views/settings/avatar.js
  tests/functional/avatar.js
Labels: train-107, waffle:active

#5941 fix(strings): change 'confirm email' design to let users know that th…
  app/scripts/views/mixins/resend-mixin.js
  app/tests/spec/views/mixins/resend-mixin.js
Labels: waffle:active

#5944 fix(styles): fix unlock button for email settings unlock
  app/scripts/templates/settings/upgrade_session.mustache
Labels: waffle:active

#5943 fix(styles): add position fixed to success messages if user scrolls t…
  app/scripts/views/base.js
  app/tests/spec/views/base.js
Labels: waffle:active

#5945 fix(css): fixes button misalignment when refreshing clients
  app/scripts/templates/settings/clients.mustache
  app/styles/modules/_settings.scss
Labels: train-107, waffle:review

#5940 feat(forms): replace our password advice with responsive message
  .editorconfig
  app/scripts/templates/sign_up.mustache
  app/scripts/templates/sign_up_password.mustache
  app/scripts/views/mixins/password-mixin.js
  app/styles/_breakpoints.scss
  app/styles/modules/_password-row.scss
  app/tests/spec/views/mixins/password-mixin.js
  app/tests/spec/views/sign_up.js
Labels: waffle:active

#5951 chore(docs): Document new entrypoint=whatsnew value.
  docs/client-metrics.md
Labels: waffle:review

#5952 fix(sign_up): changes to l10n string and style based on feedback
  app/scripts/templates/sign_up.mustache
  app/scripts/views/mixins/password-mixin.js
  app/styles/modules/_password-row.scss
  app/tests/spec/views/sign_up.js
Labels: waffle:active

#5899 feat(signin): Re-authenticate an existing session if possible.
  app/scripts/lib/fxa-client.js
  app/scripts/models/account.js
  app/scripts/models/auth_brokers/base.js
  app/scripts/models/auth_brokers/oauth.js
  app/scripts/models/auth_brokers/web.js
  app/scripts/views/mixins/signin-mixin.js
  app/scripts/views/sign_in.js
  app/tests/spec/lib/fxa-client.js
  app/tests/spec/models/account.js
  app/tests/spec/models/auth_brokers/fx-sync-channel.js
  app/tests/spec/models/auth_brokers/oauth.js
  app/tests/spec/views/mixins/signin-mixin.js
  app/tests/spec/views/sign_in.js
  npm-shrinkwrap.json
  package.json
  tests/functional/sign_in_cached.js
Labels: waffle:review

#5954 chore(typo): fix test typo in fxa-client
  app/tests/spec/lib/fxa-client.js
Labels: waffle:active

#5955 fix(token): Fix token code experiment to correctly use service
  app/scripts/lib/experiments/grouping-rules/token-code.js
  app/scripts/views/mixins/token-code-experiment-mixin.js
  app/tests/spec/lib/experiments/grouping-rules/token-code.js
Labels: waffle:active

#5953 refactor(js): remove require.js remains
  app/scripts/lib/cocktail.js
  app/scripts/lib/constants.js
  app/scripts/lib/country-telephone-info.js
  circle.yml
  grunttasks/l10n-generate-pages.js
  grunttasks/requirejs.js
  package.json
  tests/functional/complete_sign_in.js
  tests/functional/complete_sign_up.js
  tests/functional/send_sms.js
  tests/functional/sign_in_cached.js
  tests/lib/helpers.js
  tests/rjs_load.js
  tests/teamcity/install-npm-deps.sh
  tests/teamcity/run.sh
Labels: train-108, waffle:active

#5948 feat(oauth): force validate provided redirect uri
  app/scripts/lib/error-utils.js
  app/scripts/models/reliers/oauth.js
  app/tests/spec/models/reliers/oauth.js
  server/lib/configuration.js
  tests/functional/oauth_choose_redirect.js
  tests/functional/oauth_query_param_validation.js
Labels: waffle:active

#5957 fix(tests): disable profile avatar test
  tests/functional.js
  tests/functional_circle.js
Labels: waffle:active

#5959 feat(clients): Add Lockbox icon, fix Pontoon icon
  app/images/icon-service-lockbox.svg
  app/images/icon-service-pontoon.svg
  app/styles/modules/_settings.scss
Labels: waffle:review

#5964 feat(token): enable tokenCode experiment in desktopV3
  app/scripts/models/auth_brokers/fx-desktop-v3.js
  app/scripts/views/index.js
  app/scripts/views/mixins/signin-mixin.js
  app/scripts/views/sign_in.js
  app/tests/spec/models/auth_brokers/fx-desktop-v3.js
Labels: waffle:active

#5960 feat(styles): make SVG hearts beat
  app/images/account-verified-hearts.svg
  app/scripts/lib/user-agent.js
  app/scripts/templates/connect_another_device.mustache
  app/scripts/templates/sms_send.mustache
  app/scripts/templates/sms_sent.mustache
  app/scripts/views/connect_another_device.js
  app/scripts/views/sms_send.js
  app/scripts/views/sms_sent.js
  app/styles/modules/_graphic.scss
  app/tests/spec/lib/user-agent.js
  app/tests/spec/views/connect_another_device.js
  app/tests/spec/views/sms_send.js
  app/tests/spec/views/sms_sent.js
Labels: waffle:review

#5972 Release v1.106.7
  CHANGELOG.md
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#5971 fix(account): fix [object Object] errors in Sentry
  app/scripts/models/account.js
Labels: waffle:active

#5974 chore(package): update speed-trap, regenerate shrinkwrap
  npm-shrinkwrap.json
  package.json
Labels: waffle:review

#5962 feat(totp): initial totp implementation
  app/images/graphic_two_factor_auth.svg
  app/scripts/lib/auth-errors.js
  app/scripts/lib/fxa-client.js
  app/scripts/lib/router.js
  app/scripts/lib/verification-methods.js
  app/scripts/models/account.js
  app/scripts/models/auth_brokers/base.js
  app/scripts/models/auth_brokers/fx-ios-v1.js
  app/scripts/models/auth_brokers/fx-sync-web-channel.js
  app/scripts/models/auth_brokers/oauth.js
  app/scripts/templates/settings/two_step_authentication.mustache
  app/scripts/templates/sign_in_totp_code.mustache
  app/scripts/views/mixins/modal-settings-panel-mixin.js
  app/scripts/views/mixins/signin-mixin.js
  app/scripts/views/settings.js
  app/scripts/views/settings/two_step_authentication.js
  app/scripts/views/sign_in_token_code.js
  app/scripts/views/sign_in_totp_code.js
  app/styles/_modules.scss
  app/styles/modules/_custom-rows.scss
  app/styles/modules/_graphic.scss
  app/styles/modules/_modal.scss
  app/styles/modules/_settings-totp.scss
  app/tests/spec/lib/fxa-client.js
  app/tests/spec/views/settings/two_step_authentication.js
  app/tests/spec/views/sign_in_token_code.js
  app/tests/spec/views/sign_in_totp_code.js
  app/tests/test_start.js
  server/lib/routes/get-frontend.js
Labels: train-107, waffle:review

#5973 style(server templates): remove unnecessary conditional comments
  server/templates/pages/src/404.html
  server/templates/pages/src/500.html
  server/templates/pages/src/502.html
  server/templates/pages/src/503.html
  server/templates/pages/src/index.html
  server/templates/pages/src/privacy.html
  server/templates/pages/src/terms.html
Labels: waffle:backlog

#5976 refactor(metrics): Removed get-metrics-errors.js
  server/lib/routes.js
  server/lib/routes/get-metrics-errors.js
  tests/server/metrics-errors.js
  tests/server/routes.js
Labels: waffle:backlog

#5981 style(settings): Disabled the done button
  app/scripts/templates/settings/emails.mustache
Labels: waffle:review

#5980 fix(tests): add totp functional tests
  circle.yml
  package.json
  tests/functional.js
  tests/functional/lib/selectors.js
  tests/functional/oauth_sign_in.js
  tests/functional/sign_in_totp.js
  tests/functional_circle.js
  tests/teamcity/install-npm-deps.sh
  tests/teamcity/run.sh
Labels: shipit, train-108, waffle:review

#5982 feat(metrics): emit view, engage & submit events for CAD
  server/lib/amplitude.js
  tests/server/amplitude.js
Labels: waffle:active

#5989 feat(webpack): load imports from CDN
  app/scripts/app.js
  app/scripts/lib/app-start.js
  app/scripts/lib/config-loader.js
  app/scripts/lib/constants.js
  app/tests/spec/lib/app-start.js
  app/tests/spec/lib/config-loader.js
  server/lib/configuration.js
  server/lib/routes/get-index.js
  tests/server/routes/get-index.js
  webpack.config.js
Labels: shipit, train-108, waffle:review

#5946 feat(password): Check old password using sessionReauth if possible.
  app/scripts/lib/fxa-client.js
  app/scripts/models/account.js
  app/tests/spec/lib/fxa-client.js
  app/tests/spec/models/account.js
Labels: train-109, waffle:review

#5995 fix(metrics): include full version information in amplitude event data
  server/lib/amplitude.js
  tests/server/amplitude.js
Labels: waffle:review

#6000 fix(tests): fix websession test
  tests/functional/settings_clients.js
Labels: waffle:active

#5997 fix(signin): Handle deleted account and new email login afterwards
  app/scripts/views/mixins/signin-mixin.js
  app/tests/spec/views/mixins/signin-mixin.js
  tests/functional/settings.js
Labels: waffle:active

#5996 fix(server): validate ip addresses before use
  server/lib/remote-address.js
  tests/server/remote-address.js
Labels: waffle:review

#6003 fix(metrics): use $append on the experiments user property
  server/lib/amplitude.js
  tests/server/amplitude.js
Labels: waffle:active

#6004 revert(tests): fix websession test
  tests/functional/settings_clients.js
Labels: waffle:active

#6007 fix(token): end token code experiment for sync users
  app/scripts/lib/experiments/grouping-rules/token-code.js
  app/scripts/models/auth_brokers/fx-desktop-v3.js
  app/scripts/models/reliers/sync.js
  app/tests/spec/models/auth_brokers/fx-desktop-v3.js
Labels: train-108, waffle:review

#6011 fix(node): Use Node.js v6.14.0
  Dockerfile-build
Labels: waffle:active

#6008 fix(metrics): ensure CAD view and engage events are correct
  server/lib/amplitude.js
  tests/server/amplitude.js
Labels: waffle:active

#6010 fix(oauth): fix password reset for scoped reliers verifying in same b…
  app/scripts/models/account.js
  app/scripts/models/auth_brokers/oauth.js
  app/scripts/views/confirm_reset_password.js
  app/tests/spec/views/confirm_reset_password.js
Labels: train-109, waffle:active
