Repository mozilla/fxa-content-server, pull requests merged in 2018-10, with the labels that each got.

#6597 fix(scripts): make tls-shrink script portable
  scripts/tls-shrink.sh
Labels: waffle:review

#6600 chore(config): Add scoped-keys configuration for Firefox Send.
  server/lib/configuration.js
Labels: waffle:active

#6579 fix(email): on password reset, hash email with the `emailToHashWith` value
  app/scripts/models/account.js
  app/scripts/models/user.js
  app/scripts/views/complete_reset_password.js
  app/tests/spec/models/user.js
  tests/functional/settings_change_email.js
Labels: train-122:qa-needed, waffle:review

#6598 fix(ci): use npm 6 in travis
  .travis.yml
Labels: train-122, waffle:active

#6596 chore(deps): Update to the latest i18n-abide to get rid of security warnings.
  npm-shrinkwrap.json
  package.json
Labels: train-122, waffle:review

#6589 feat(email-first): Allow invalid emails in query params.
  app/scripts/models/reliers/relier.js
  app/scripts/models/reliers/sync.js
  app/scripts/views/index.js
  app/tests/spec/models/reliers/oauth.js
  app/tests/spec/models/reliers/relier.js
  tests/functional/oauth_email_first.js
  tests/functional/sign_up.js
  tests/functional/sync_v3_email_first.js
Labels: train-122, train-122:qa-needed, waffle:review

#6603 chore(release): Merge train-122 into master
  CHANGELOG.md
  package.json
Labels: waffle:active

#6604 chore(release): Reverse merge -private repo changes to public's train-122
  CHANGELOG.md
  app/scripts/lib/constants.js
  app/scripts/lib/crypto/recovery-keys.js
  app/scripts/lib/experiments/grouping-rules/recovery-key.js
  app/styles/modules/_settings-account-recovery.scss
  app/tests/spec/lib/crypto/recovery-keys.js
Labels: waffle:active

#6605 chore(release): Merge train 122 into master
  CHANGELOG.md
  app/scripts/lib/constants.js
  app/scripts/lib/crypto/recovery-keys.js
  app/scripts/lib/experiments/grouping-rules/recovery-key.js
  app/styles/modules/_settings-account-recovery.scss
  app/tests/spec/lib/crypto/recovery-keys.js
  package.json
Labels: waffle:active

#6606 feat(routes): add support for .well-known/change-password
  server/lib/routes.js
  server/lib/routes/get-well-known-change-password.js
  tests/server/routes/get-well-known-change-password.js
  tests/tests_server.js
Labels: waffle:active

#6608 feat(sms): add padlock to sms submit form
  app/images/icon-secure-lock.svg
  app/scripts/templates/sms_send.mustache
  app/styles/modules/_branding.scss
Labels: waffle:active

#6607 fix(force_auth): mention service name in force_auth
  app/scripts/templates/force_auth.mustache
  app/scripts/views/force_auth.js
  app/tests/spec/views/force_auth.js
Labels: waffle:active

#6610 fix(links): Remove `en-US` from any SUMO/MDN links.
  app/scripts/lib/channels/receivers/web-channel.js
  app/scripts/lib/channels/senders/web-channel.js
  app/scripts/lib/channels/web.js
  app/scripts/lib/user-agent.js
  app/scripts/views/settings/two_step_authentication.js
  app/scripts/views/sms_send.js
  app/tests/mocks/broadcast-channel.js
  app/tests/spec/views/settings/two_step_authentication.js
Labels: waffle:review

#6624 Train 122 uplift 121
  CHANGELOG.md
  app/scripts/lib/channels/receivers/web-channel.js
  app/scripts/lib/channels/senders/web-channel.js
  app/scripts/lib/channels/web.js
  app/scripts/lib/experiments/grouping-rules/recovery-key.js
  app/scripts/lib/user-agent.js
  app/scripts/views/settings/two_step_authentication.js
  app/scripts/views/sms_send.js
  app/tests/mocks/broadcast-channel.js
  app/tests/spec/views/settings/two_step_authentication.js
Labels: waffle:review

#6625 chore(release): Merge train 122 into master
  CHANGELOG.md
  app/scripts/lib/channels/receivers/web-channel.js
  app/scripts/lib/channels/senders/web-channel.js
  app/scripts/lib/channels/web.js
  app/scripts/lib/experiments/grouping-rules/recovery-key.js
  app/scripts/lib/user-agent.js
  app/scripts/views/settings/two_step_authentication.js
  app/scripts/views/sms_send.js
  app/tests/mocks/broadcast-channel.js
  app/tests/spec/views/settings/two_step_authentication.js
  package.json
Labels: waffle:active

#6628 chore(recovery): enable recovery key for 100% users
  app/scripts/lib/experiments/grouping-rules/recovery-key.js
Labels: train-122, waffle:active

#6629 Uplift Train 122 to master
  CHANGELOG.md
  app/scripts/lib/experiments/grouping-rules/recovery-key.js
  package.json
Labels: waffle:active

#6633 fix(copy):Changed enter code to use code
  app/scripts/templates/sign_in_recovery_code.mustache
Labels: waffle:active

#6631 fix(test): Upgrade intern to 4.3.1 so tests run in fx 63
  npm-shrinkwrap.json
  package.json
Labels: waffle:review

#6636 fix(emails): add recovery key images
  app/images/recovery_key/confirm_revoke.png
  app/images/recovery_key/download_key.png
  app/images/recovery_key/generate_new.png
  app/images/recovery_key/revoke_key.png
  grunttasks/rev.js
Labels: waffle:active

#6630 fix(totp): call proto `afterCompleteSignInWithCode` after entering valid totp code
  app/scripts/models/auth_brokers/fx-ios-v1.js
  app/tests/spec/models/auth_brokers/fx-ios-v1.js
Labels: train-123, train-123:qa-needed, waffle:review

#6639 fix(metrics): stop sending metrics context to deprecated endpoints
  app/scripts/lib/fxa-client.js
  app/tests/spec/lib/fxa-client.js
  npm-shrinkwrap.json
  package.json
Labels: train-123, waffle:review

#6637 fix(checkbox): adds some margin to checkboxes
  app/styles/modules/_custom-rows.scss
Labels: train-123, train-123:qa-needed, waffle:review

#6640 chore(release): Merge train-123 into master
  CHANGELOG.md
  package.json
Labels: waffle:review

#6644 feat(connect-device): allow showSuccessMessage search param
  app/scripts/views/connect_another_device.js
  app/tests/spec/views/connect_another_device.js
Labels: waffle:active

#6647 refactor(creds): remove support for `email=blank`, disabling of cache…
  app/scripts/lib/constants.js
  app/scripts/models/reliers/base.js
  app/scripts/models/reliers/relier.js
  app/scripts/templates/sign_in.mustache
  app/scripts/views/mixins/cached-credentials-mixin.js
  app/tests/spec/models/reliers/base.js
  app/tests/spec/models/reliers/relier.js
  app/tests/spec/views/mixins/cached-credentials-mixin.js
  app/tests/spec/views/sign_in.js
  tests/functional/sign_in_cached.js
Labels: waffle:active

#6646 feat(Lockbox): Add Lockbox for Android scopes to configuration
  server/lib/configuration.js
Labels: train-123, waffle:review

#6648 chore(release): Merge v1.123.1 point release to master
  CHANGELOG.md
  package.json
  server/lib/configuration.js
Labels: waffle:review

#6641 feat(pairing): The channel server for the pairing flow.
  app/scripts/lib/channel-server-client-errors.js
  app/scripts/lib/channel-server-client.js
  app/scripts/lib/constants.js
  app/tests/spec/lib/channel-server-client.js
  app/tests/test_start.js
  package.json
Labels: train-124, waffle:review

#6651 feat(metrics): No longer send events to Google Analytics
  npm-shrinkwrap.json
  package.json
  server/lib/configuration.js
  server/lib/ga-collector.js
  server/lib/routes/post-metrics.js
  tests/server/fixtures/ga_body_1.json
  tests/server/fixtures/ga_body_screen.json
  tests/server/metrics-ga.js
  tests/server/metrics-unit.js
  tests/server/routes/post-metrics.js
  tests/teamcity/install-npm-deps.sh
  tests/tests_server.js
Labels: waffle:active

#6545 fix(codes): support requesting totp verification on sign-in
  app/scripts/lib/auth-errors.js
  app/scripts/lib/constants.js
  app/scripts/lib/oauth-errors.js
  app/scripts/models/auth_brokers/base.js
  app/scripts/models/auth_brokers/oauth.js
  app/scripts/models/reliers/base.js
  app/scripts/models/reliers/oauth.js
  app/scripts/views/mixins/signin-mixin.js
  app/scripts/views/sign_in_password.js
  app/tests/spec/models/auth_brokers/oauth.js
  app/tests/spec/models/reliers/oauth.js
  app/tests/spec/views/mixins/signin-mixin.js
  tests/functional/lib/selectors.js
  tests/functional/oauth_require_totp.js
  tests/functional_oauth.js
Labels: train-124, waffle:review

#6659 fix(codes): Dont allow `wantsTwoStepAuthentication` to bypass the password prompt
  app/scripts/views/sign_in_password.js
  tests/functional/oauth_require_totp.js
Labels: waffle:active

#6663 fix(ci): update travis to use oauth server in auth server repo
  .travis.yml
  tests/ci/deps.sh
Labels: waffle:review

#6664 fix(metrics): fix get-metrics-flow to use correct view event
  .travis.yml
  server/lib/routes/get-metrics-flow.js
  tests/ci/deps.sh
  tests/server/routes/get-metrics-flow.js
Labels: waffle:active

#6671 fix(deps): Fix the npm audit warnings in jsxgettext-recursive
  grunttasks/l10n-extract.js
  npm-shrinkwrap.json
  package.json
Labels: security, train-124, waffle:active

#6672 fix(deps): Fix the npm audit warning for sync-exec
  npm-shrinkwrap.json
  package.json
  tests/tools/firefox_profile.js
Labels: train-124, waffle:review

#6673 fix(ci): Remove sync-exec from CI dep installation
  .circleci/config.yml
  tests/teamcity/install-npm-deps.sh
  tests/teamcity/run.sh
Labels: train-124, waffle:review

#6674 fix(pairing): Expect the channelId to be a base64url string.
  app/scripts/lib/channel-server-client.js
  app/tests/spec/lib/channel-server-client.js
Labels: pairing/web content, shipit, waffle:review

#6675 fix(totp): Remove en-US from the TOTP SUMO link.
  app/scripts/views/mixins/signin-mixin.js
  app/tests/spec/views/mixins/signin-mixin.js
  grunttasks/ban-word.js
Labels: shipit, train-124, train-124:qa-needed, waffle:review

#6676 fix(deps): add filtered npm audit
  .nsprc
  .travis.yml
  npm-shrinkwrap.json
  package.json
Labels: shipit, train-124, waffle:review

#6680 chore(deps): Use speed-trap from npm instead of a git url
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#6681 chore(deps): update mailcheck
  npm-shrinkwrap.json
  package.json
Labels: train-125, waffle:review

#6677 chore(release): Merge train-124 into master
  AUTHORS
  CHANGELOG.md
  package.json
Labels: waffle:review

#6682 refactor(pw-strength): Remove designF's "experiment" status.
  app/scripts/lib/experiment.js
  app/scripts/lib/experiments/grouping-rules/index.js
  app/scripts/lib/experiments/grouping-rules/password-strength.js
  app/scripts/lib/experiments/password-strength.js
  app/scripts/templates/sign_up_password.mustache
  app/scripts/views/mixins/password-strength-mixin.js
  app/scripts/views/sign_up_password.js
  app/tests/spec/lib/experiments/grouping-rules/index.js
  app/tests/spec/lib/experiments/grouping-rules/password-strength.js
  app/tests/spec/lib/experiments/password-strength.js
  app/tests/spec/views/mixins/password-strength-experiment-mixin.js
  app/tests/spec/views/mixins/password-strength-mixin.js
  app/tests/spec/views/sign_up_password.js
  app/tests/test_start.js
  tests/functional.js
  tests/functional/fx_firstrun_v2_email_first.js
  tests/functional/lib/helpers.js
  tests/functional/oauth_email_first.js
  tests/functional/password_strength.js
  tests/functional/send_sms.js
  tests/functional/sync_v3_email_first.js
  tests/functional_circle.js
Labels: train-125, waffle:review
