Repository mozilla/fxa-content-server, pull requests merged in 2018-02, with the labels that each got.

#5896 feat(styles): improve reset password for reliers
  app/scripts/models/auth_brokers/web.js
  app/scripts/templates/complete_reset_password.mustache
  app/scripts/templates/confirm_reset_password.mustache
  app/scripts/templates/reset_password.mustache
  app/scripts/views/ready.js
  app/scripts/views/reset_password.js
  app/styles/_base.scss
  app/styles/_state.scss
  app/styles/_variables.scss
  app/styles/modules/_button-row.scss
  app/tests/spec/views/reset_password.js
  tests/functional/lib/selectors.js
  tests/functional/reset_password.js
Labels: waffle:active

#5901 refactor(docs): link the policy page to the different doc
  grunttasks/replace.js
  grunttasks/yeoman.js
Labels: shipit, train-105, waffle:active

#5903 fix(style): swap reset links per feedback
  app/scripts/templates/confirm_reset_password.mustache
Labels: waffle:active

#5904 refactor(strings): remove "cloud services"
  app/scripts/templates/force_auth.mustache
  app/scripts/templates/index.mustache
  app/scripts/templates/legal.mustache
  app/scripts/templates/pp.mustache
  app/scripts/templates/sign_in.mustache
  app/scripts/templates/sign_up.mustache
  app/scripts/templates/sign_up_password.mustache
  app/scripts/templates/tos.mustache
  server/templates/pages/src/privacy.html
  server/templates/pages/src/terms.html
Labels: waffle:active

#5911 fix(deps): adjust speed-trap dep and fix nsp issue
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#5913 revert(tokencode): revert isSync detection
  app/scripts/lib/experiments/grouping-rules/token-code.js
  app/tests/spec/lib/experiments/grouping-rules/token-code.js
Labels: waffle:active

#5910 fix(strings): update communication pref strings
  app/scripts/templates/settings/communication_preferences.mustache
Labels: waffle:review

#5909 fix(styles): fix icon overlap in CWTS on iOS
  app/styles/modules/_branding.scss
Labels: waffle:active

#5915 refactor(deps): remove bower
  .bowerrc
  .eslintignore
  .gitignore
  .travis.yml
  CONTRIBUTING.md
  Dockerfile-build
  app/styles/_modules.scss
  app/styles/main.scss
  app/tests/lib/blanket_lcov.js
  app/tests/test_start.js
  bower.json
  circle.yml
  docs/architecture.md
  grunttasks/concat.js
  grunttasks/concurrent.js
  grunttasks/copy.js
  grunttasks/copyright.js
  grunttasks/jsonlint.js
  grunttasks/rev.js
  grunttasks/todo.js
  grunttasks/watch.js
  grunttasks/yeoman.js
  locale/README.md
  npm-shrinkwrap.json
  package.json
  server/lib/configuration.js
  server/lib/version.js
  server/templates/pages/src/404.html
  server/templates/pages/src/500.html
  server/templates/pages/src/502.html
  server/templates/pages/src/503.html
  server/templates/pages/src/index.html
  server/templates/pages/src/privacy.html
  server/templates/pages/src/terms.html
  tests/server/amplitude.js
  tests/server/flow-event.js
  tests/server/flow-metrics.js
  tests/server/html-middleware.js
  tests/server/routes/post-metrics.js
  tests/teamcity/install-npm-deps.sh
  tests/teamcity/run.sh
  webpack.config.js
Labels: waffle:review

#5920 fix(nsp): disable nsp 566
  .nsprc
Labels: waffle:active

#5908 fix(copy):Show email section to view status
  app/scripts/templates/settings/upgrade_session.mustache
Labels: train-106, waffle:active

#5918 fix(experiment): fix the token code experiment
  app/scripts/lib/experiments/grouping-rules/token-code.js
  app/tests/spec/lib/experiments/grouping-rules/token-code.js
Labels: train-106, waffle:review

#5917 chore(password): graduate confirm password experiment
  app/scripts/lib/experiment.js
  app/scripts/lib/experiments/grouping-rules/index.js
  app/scripts/lib/experiments/grouping-rules/q3-form-changes.js
  app/scripts/lib/experiments/grouping-rules/signup-password-confirm.js
  app/scripts/templates/sign_up.mustache
  app/scripts/views/sign_up.js
  app/tests/spec/lib/experiments/grouping-rules/email-first.js
  app/tests/spec/lib/experiments/grouping-rules/signup-password-confirm.js
  app/tests/spec/views/sign_up.js
  app/tests/test_start.js
  tests/functional/lib/helpers.js
  tests/functional/sign_up.js
Labels: train-106, waffle:review

#5905 fix(errors): ensure that toError always behaves sanely
  app/scripts/lib/errors.js
  app/tests/spec/lib/auth-errors.js
Labels: train-106, waffle:review

#5923 fix(config): if "10 minutes" then duration not Number
  server/lib/configuration.js
Labels: waffle:active

#5924 fix(metrics): treat enter-email as an "auth" view for flow events
  server/lib/flow-event.js
  tests/server/flow-event.js
Labels: shipit, train-106, waffle:review

#5926 feat(code): enable token code experiment sync users for 1.8% each cohort
  app/scripts/lib/experiments/grouping-rules/token-code.js
Labels: train-106

#5803 fix(settingView): All panels will be closed while navigating from a childview to settings.
  app/scripts/views/settings.js
Labels: train-107, waffle:active

#5867 fix(basket): Show service unavaible when no basket account prefs set
  app/scripts/lib/marketing-email-errors.js
  app/scripts/views/settings/communication_preferences.js
  app/tests/spec/views/settings/communication_preferences.js
Labels: waffle:review

#5928 fix(tests): fixes for oauth tests and reset password
  app/scripts/views/reset_password.js
  app/tests/spec/views/reset_password.js
  tests/functional/force_auth.js
  tests/functional/oauth_permissions.js
Labels: waffle:active

#5929 Uplift v1.106.3 into master
  CHANGELOG.md
  app/scripts/views/reset_password.js
  app/tests/spec/views/reset_password.js
  package.json
  tests/functional/force_auth.js
  tests/functional/oauth_permissions.js
Labels: waffle:active
