Repository mozilla/fxa-content-server, pull requests merged in 2018-09, with the labels that each got.

#6511 fix(style): fix missing recovery code icons
  app/scripts/templates/settings/account_recovery/recovery_key.mustache
  app/styles/modules/_settings-account-recovery.scss
Labels: waffle:review

#6500 fix(codes): update token code requirements
  app/scripts/lib/auth-errors.js
  app/scripts/lib/constants.js
  app/scripts/templates/sign_in_token_code.mustache
  app/scripts/views/elements/jquery-plugin.js
  app/scripts/views/elements/token-code-input.js
  app/scripts/views/sign_in_token_code.js
  app/tests/spec/views/elements/token-code-input.js
  app/tests/spec/views/sign_in_token_code.js
  app/tests/test_start.js
  tests/functional/lib/helpers.js
  tests/functional/lib/selectors.js
  tests/functional/sign_in_token_code.js
Labels: shipit, train-120, waffle:review

#6518 fix(codes): fix token code regex and error message
  app/scripts/lib/auth-errors.js
  app/scripts/views/elements/token-code-input.js
Labels: waffle:active

#6521 feat(pw-strength): 50% to Arabic, 100% in German
  app/scripts/lib/experiments/grouping-rules/password-strength.js
  app/scripts/views/mixins/password-strength-experiment-mixin.js
  app/scripts/views/password_strength/password_with_strength_balloon.js
  app/tests/spec/lib/experiments/grouping-rules/password-strength.js
Labels: waffle:review

#6522 fix(metrics): send events from /metrics-flow to amplitude
  server/lib/routes/get-metrics-flow.js
  tests/server/routes/get-metrics-flow.js
Labels: waffle:active

#6523 chore(release): Uplift train 120 to master
  CHANGELOG.md
  app/scripts/lib/experiments/grouping-rules/password-strength.js
  app/scripts/views/mixins/password-strength-experiment-mixin.js
  app/scripts/views/password_strength/password_with_strength_balloon.js
  app/tests/spec/lib/experiments/grouping-rules/password-strength.js
  package.json
Labels: waffle:active

#6480 feat(router): Groundwork to load views on demand.
  app/scripts/lib/router.js
  app/scripts/views/base.js
  app/scripts/views/mixins/modal-settings-panel-mixin.js
  app/tests/spec/lib/router.js
  app/tests/spec/views/mixins/modal-settings-panel-mixin.js
  package.json
  webpack.config.js
Labels: waffle:active

#6532 chore(modules): Convert from `require` to `import` in app-start.js
  app/scripts/lib/app-start.js
Labels: waffle:review

#6538 fix(codes): continue sign-in progress after generating from low recovery codes
  app/scripts/views/settings/recovery_codes.js
  app/tests/spec/views/settings/recovery_codes.js
Labels: waffle:active

#6541 Uplift Train 120
  CHANGELOG.md
  app/scripts/views/settings/recovery_codes.js
  app/tests/spec/views/settings/recovery_codes.js
  package.json
Labels: waffle:active

#6539 fix(code): fix some lgtm analysis warnings
  app/scripts/lib/channels/senders/fx-desktop-v1.js
  app/scripts/lib/mailcheck.js
  app/scripts/views/account_recovery_confirm_key.js
  app/scripts/views/settings.js
  app/scripts/views/settings/avatar_crop.js
  grunttasks/eslint.js
  server/lib/ga-collector.js
Labels: train-121, waffle:review

#6551 feat(pw-strength): All ltr users see designF, 50/50 split for Arabic
  app/scripts/lib/experiments/grouping-rules/password-strength.js
  app/scripts/views/mixins/password-strength-experiment-mixin.js
  app/tests/spec/lib/experiments/grouping-rules/password-strength.js
  app/tests/spec/views/mixins/password-strength-experiment-mixin.js
Labels: waffle:review

#6549 chore(codes): update clients for token code experiment
  app/scripts/lib/experiments/grouping-rules/token-code.js
  app/scripts/views/mixins/token-code-experiment-mixin.js
  app/tests/spec/lib/experiments/grouping-rules/token-code.js
Labels: waffle:review

#6552 fix(email-first): Disallow firefox.com addresses for email first
  app/scripts/views/index.js
  app/tests/spec/views/index.js
  tests/functional/lib/selectors.js
  tests/functional/sync_v3_email_first.js
Labels: waffle:review

#6555 fix(recovery): add account recovery reason property for metrics
  app/scripts/lib/fxa-client.js
  app/scripts/lib/verification-reasons.js
  app/tests/spec/lib/fxa-client.js
Labels: waffle:active

#6557 chore(release): Merge train 120 into master
  CHANGELOG.md
  app/scripts/lib/experiments/grouping-rules/password-strength.js
  app/scripts/lib/experiments/grouping-rules/token-code.js
  app/scripts/lib/fxa-client.js
  app/scripts/lib/verification-reasons.js
  app/scripts/views/mixins/password-strength-experiment-mixin.js
  app/scripts/views/mixins/token-code-experiment-mixin.js
  app/tests/spec/lib/experiments/grouping-rules/password-strength.js
  app/tests/spec/lib/experiments/grouping-rules/token-code.js
  app/tests/spec/lib/fxa-client.js
  app/tests/spec/views/mixins/password-strength-experiment-mixin.js
  package.json
Labels: waffle:active

#6544 refactor(metrics): remove datadog metrics
  app/scripts/lib/experiments/grouping-rules/is-sampled-user.js
  app/scripts/lib/metrics.js
  npm-shrinkwrap.json
  package.json
  server/lib/configuration.js
  server/lib/routes/post-metrics.js
  server/lib/statsd-collector.js
  tests/server/fixtures/statsd_body_1.json
  tests/server/fixtures/statsd_body_2.json
  tests/server/fixtures/statsd_body_filter_out_of_range.json
  tests/server/metrics-unit.js
  tests/server/routes/post-metrics.js
  tests/server/statsd-collector.js
  tests/teamcity/install-npm-deps.sh
  tests/tests_server.js
Labels: train-122, waffle:review

#6560 fix(codes): enable recovery key for 10% users
  app/scripts/lib/experiments/grouping-rules/recovery-key.js
Labels: shipit, train-121, waffle:review

#6563 feat(pw-strength): Fully roll out designF everywhere.
  app/scripts/lib/experiments/grouping-rules/password-strength.js
  app/tests/spec/lib/experiments/grouping-rules/password-strength.js
Labels: shipit, train-121, waffle:review

#6565 chore(release): Merge train-121 into master
  CHANGELOG.md
  package.json
Labels: waffle:active

#6558 fix(show-password): Use a show-password icon that works on low DPI screens.
  app/images/icon-show-password.svg
Labels: train-122, waffle:review

#6576 chore(package): bump fxa-shared to 1.0.14 + npm shrinkwrap
  npm-shrinkwrap.json
  package.json
Labels: waffle:review

#6583 fix(test): Force clear localStorage for the handshake tests.
  tests/functional/oauth_handshake.js
Labels: train-122, waffle:review

#6586 refactor(pairing): Extract a `required` module.
  app/scripts/lib/crypto/recovery-keys.js
  app/scripts/lib/crypto/scoped-keys.js
  app/scripts/lib/required.js
  app/scripts/views/mixins/sync-suggestion-mixin.js
  app/tests/spec/lib/crypto/recovery-keys.js
  app/tests/spec/lib/crypto/scoped-keys.js
  app/tests/spec/views/mixins/sync-suggestion-mixin.js
Labels: waffle:review

#6587 refactor(pairing): Extract hkdf into its own module.
  app/scripts/lib/crypto/hkdf.js
  app/scripts/lib/crypto/recovery-keys.js
  app/tests/spec/lib/crypto/hkdf.js
  app/tests/test_start.js
Labels: waffle:review

#6590 fix(CWTS): Fix the checkbox alignment in RTL langugates.
  app/styles/modules/_custom-rows.scss
Labels: train-122, train-122:qa-needed, waffle:review

#6592 refactor(pairing): Convert lib/channels/web.js to ES6 module format.
  app/scripts/lib/channels/web.js
  app/tests/spec/lib/channels/web.js
Labels: waffle:active

#6591 refactor(pairing): Extract validate and vat formatting updates
  app/scripts/lib/validate.js
  app/scripts/lib/vat.js
  app/tests/spec/lib/validate.js
Labels: train-122, waffle:review

#6588 refactor(pairing): Extract a256gcm related utils into its own module.
  app/scripts/lib/crypto/a256gcm.js
  app/scripts/lib/crypto/recovery-keys.js
  app/tests/spec/lib/crypto/a256gcm.js
  app/tests/test_start.js
  grunttasks/ban-word.js
  grunttasks/lint.js
  npm-shrinkwrap.json
  package.json
Labels: train-122, waffle:review
