Repository mozilla/fxa-content-server, pull requests merged in 2018-07, with the labels that each got.

#6334 fix(test): Fix the failing URL tests caused by the Firefox Privacy Policy
  tests/server/helpers/routesHelpers.js
Labels: train-116, waffle:review

#6332 feat(test): Show more helpful error messages for the route check.
  tests/server/helpers/routesHelpers.js
  tests/server/l10n-entrained.js
  tests/server/routes.js
Labels: waffle:active

#6337 fix(form): Catch the form validation errors, no more console message.
  app/scripts/views/form.js
  app/tests/spec/views/form.js
Labels: train-116, waffle:active

#6338 fix(pw-strength): Make the pw-strength balloon more a11y friendly.
  app/scripts/templates/partial/password-strength-balloon.mustache
  app/scripts/views/form.js
  app/scripts/views/mixins/password-strength-experiment-mixin.js
  app/scripts/views/password_strength/password_with_strength_balloon.js
  app/tests/spec/views/form.js
  app/tests/spec/views/mixins/password-strength-experiment-mixin.js
  app/tests/spec/views/password_strength/password_with_strength_balloon.js
Labels: train-116, waffle:active

#6341 fix(pw-strength): Ban service names anywhere in password if > 1/2 of password.
  app/scripts/models/password_strength/password_strength_balloon.js
  app/tests/spec/models/password_strength/password_strength_balloon.js
Labels: train-116, train-116:qa-needed, waffle:review

#6305 fix(password-reset): Update the password reset text for clarity.
  app/scripts/templates/complete_reset_password.mustache
  app/scripts/templates/reset_password.mustache
Labels: train-117, waffle:review

#6340 fix(pw-strength): Immediately update pw balloon on submit
  app/scripts/models/password_strength/password_strength_balloon.js
  app/scripts/views/form.js
  app/scripts/views/mixins/password-strength-experiment-mixin.js
  app/scripts/views/password_strength/password_strength_balloon.js
  app/scripts/views/password_strength/password_with_strength_balloon.js
  app/tests/spec/models/password_strength/password_strength_balloon.js
  app/tests/spec/views/form.js
  app/tests/spec/views/mixins/password-strength-experiment-mixin.js
  app/tests/spec/views/password_strength/password_strength_balloon.js
  app/tests/spec/views/password_strength/password_with_strength_balloon.js
  tests/functional/lib/helpers.js
  tests/functional/password_strength_experiment.js
Labels: shipit, train-116, waffle:review

#6342 fix(metrics): force utm_source=email when signing in from CAD
  app/scripts/lib/constants.js
  app/scripts/views/connect_another_device.js
  app/tests/spec/views/connect_another_device.js
Labels: shipit, train-116, waffle:review

#6348 fix(circle): run tests on a node8 box
  circle.yml
Labels: waffle:active

#6350 chore(release): Merge train-116 into master
  AUTHORS
  CHANGELOG.md
  package.json
Labels: waffle:active

#6353 fix(pw-strength): Report password strength metrics to amplitude
  app/scripts/lib/experiments/password-strength.js
  app/tests/spec/lib/experiments/password-strength.js
  npm-shrinkwrap.json
  package.json
  server/lib/amplitude.js
  tests/server/amplitude.js
Labels: train-116, waffle:review

#6356 chore(release): merge train 116 into master
  CHANGELOG.md
  app/scripts/lib/experiments/password-strength.js
  app/tests/spec/lib/experiments/password-strength.js
  npm-shrinkwrap.json
  package.json
  server/lib/amplitude.js
  tests/server/amplitude.js
Labels: waffle:active

#6359 fix(image): use smaller 2FA images on sign-in
  app/styles/modules/_graphic.scss
Labels: waffle:active

#6308 feat(style): Use the Photon checkbox styling.
  app/images/icon-check-white.svg
  app/scripts/templates/choose_what_to_sync.mustache
  app/scripts/templates/partial/permission.mustache
  app/scripts/templates/sign_up.mustache
  app/scripts/templates/sign_up_password.mustache
  app/scripts/views/choose_what_to_sync.js
  app/scripts/views/mixins/checkbox-mixin.js
  app/scripts/views/permissions.js
  app/scripts/views/sign_up.js
  app/scripts/views/sign_up_password.js
  app/styles/_modules.scss
  app/styles/modules/_custom-rows.scss
  app/tests/spec/views/mixins/checkbox-mixin.js
  app/tests/test_start.js
  npm-shrinkwrap.json
  package.json
  webpack.config.js
Labels: a11y, train-117, waffle:review

#6365 fix(oauth): handle '+' in scope normalization
  app/scripts/models/reliers/oauth.js
  app/tests/spec/models/reliers/oauth.js
Labels: waffle:active

#6355 feat(pw-strength): Enable the experiment for 10% of users.
  app/scripts/lib/experiments/grouping-rules/password-strength.js
Labels: train-116, waffle:review

#6369 fix(pw-reset): Ensure pw reset completes w/ uid & email specified in email
  app/scripts/models/verification/same-browser.js
  app/tests/spec/models/verification/same-browser.js
Labels: train-116, waffle:active

#6367 Uplift train-116 to master
  CHANGELOG.md
  app/scripts/lib/experiments/grouping-rules/password-strength.js
  app/scripts/models/reliers/oauth.js
  app/scripts/models/verification/same-browser.js
  app/tests/spec/models/reliers/oauth.js
  app/tests/spec/models/verification/same-browser.js
  package.json
Labels: waffle:active

#6366 chore(docs): remove old server box
  README.md
Labels: waffle:active

#6363 refactor(modules): Convert a bunch of modules to ES6 format
  app/scripts/lib/router.js
  app/scripts/models/auth_brokers/oauth.js
  app/scripts/views/confirm.js
  app/scripts/views/confirm_reset_password.js
  app/scripts/views/force_auth.js
  app/scripts/views/index.js
  app/scripts/views/oauth_index.js
  app/scripts/views/permissions.js
  app/scripts/views/sign_in_recovery_code.js
  app/scripts/views/sign_in_token_code.js
  app/scripts/views/sign_in_totp_code.js
  app/scripts/views/sign_in_unblock.js
  app/tests/spec/lib/router.js
  app/tests/spec/models/auth_brokers/oauth.js
  app/tests/spec/views/authorization.js
  app/tests/spec/views/confirm_reset_password.js
  app/tests/spec/views/index.js
  app/tests/spec/views/oauth_index.js
  app/tests/spec/views/sign_in_unblock.js
Labels: waffle:active

#6373 refactor(deps): Remove SearchParamMixin where unneeded.
  app/scripts/views/index.js
  app/scripts/views/mixins/signin-mixin.js
  app/scripts/views/settings/emails.js
Labels: waffle:review

#6374 refactor(mixins): Remove SigninMixin from views where it isn't used.
  app/scripts/views/sign_in_recovery_code.js
  app/scripts/views/sign_in_token_code.js
  app/scripts/views/sign_in_totp_code.js
Labels: waffle:active

#6377 fix(pw-strength): "password_missing" no longer emit when view is shown
  app/scripts/models/password_strength/password_strength_balloon.js
  app/scripts/views/mixins/password-strength-experiment-mixin.js
  app/tests/spec/models/password_strength/password_strength_balloon.js
  app/tests/spec/views/mixins/password-strength-experiment-mixin.js
Labels: train-116, waffle:review

#6378 chore(release): Merge train-116 into master
  CHANGELOG.md
  app/scripts/models/password_strength/password_strength_balloon.js
  app/scripts/views/mixins/password-strength-experiment-mixin.js
  app/tests/spec/models/password_strength/password_strength_balloon.js
  app/tests/spec/views/mixins/password-strength-experiment-mixin.js
  package.json
Labels: waffle:review

#6381 fix(test): Fix the checkbox clicking functional tests
  package.json
  tests/functional/lib/selectors.js
  tests/functional/sync_sign_up.js
Labels: train-117, waffle:review

#6386 fix(sms): Fix the failing send_sms tests
  tests/functional/send_sms.js
Labels: train-117, waffle:review

#6385 fix(oauth): Fix `login_hint` support
  app/scripts/models/reliers/oauth.js
  app/tests/spec/models/reliers/oauth.js
  tests/functional/oauth_email_first.js
Labels: oauth, train-117, train-117:qa-needed, waffle:review

#6361 refactor(router): Do all link transformation from the router.
  app/scripts/lib/app-start.js
  app/scripts/lib/router.js
  app/scripts/models/auth_brokers/oauth.js
  app/scripts/views/authorization.js
  app/scripts/views/confirm.js
  app/scripts/views/confirm_reset_password.js
  app/scripts/views/force_auth.js
  app/scripts/views/index.js
  app/scripts/views/oauth_index.js
  app/scripts/views/permissions.js
  app/scripts/views/sign_in_recovery_code.js
  app/scripts/views/sign_in_token_code.js
  app/scripts/views/sign_in_totp_code.js
  app/scripts/views/sign_in_unblock.js
  app/tests/spec/lib/router.js
  app/tests/spec/models/auth_brokers/oauth.js
  app/tests/spec/views/authorization.js
  app/tests/spec/views/confirm_reset_password.js
  app/tests/spec/views/index.js
  app/tests/spec/views/oauth_index.js
  app/tests/spec/views/sign_in_unblock.js
Labels: train-117, waffle:review

#6387 chore(release): Merge train-117 into master
  AUTHORS
  CHANGELOG.md
  package.json
Labels: waffle:active

#6390 chore(es6): Convert sign_in_* to use ES6 modules.
  app/scripts/views/sign_in.js
  app/scripts/views/sign_in_password.js
  app/tests/spec/views/sign_in.js
  app/tests/spec/views/sign_in_password.js
Labels: train-118, waffle:active

#6376 Upgrade to webpack 4
  .eslintrc
  app/scripts/lib/fxa-client.js
  npm-shrinkwrap.json
  package.json
  webpack.config.js
Labels: train-118, waffle:active

#6393 chore(install): Only clone the l10n repo if needed.
  scripts/download_l10n.sh
Labels: waffle:active

#6382 feat(test): All helper failures cause a screenshot to be taken.
  tests/functional/lib/helpers.js
Labels: train-118, waffle:review

#6351 Modernize Css build pipeline
  .gitignore
  README.md
  app/styles/_variables.scss
  app/styles/fontello.scss
  app/styles/main.scss
  app/styles/postcss.config.js
  grunttasks/build.js
  grunttasks/css.js
  grunttasks/sass.js
  grunttasks/server.js
  grunttasks/watch.js
  npm-shrinkwrap.json
  package.json
  server/bin/fxa-content-server.js
  server/templates/pages/src/404.html
  server/templates/pages/src/500.html
  server/templates/pages/src/502.html
  server/templates/pages/src/503.html
  server/templates/pages/src/index.html
  server/templates/pages/src/privacy.html
  server/templates/pages/src/terms.html
  webpack.config.js
Labels: waffle:active

#6360 feat(email-first): Use cached creds if available in email-first
  app/scripts/models/auth_brokers/oauth.js
  app/scripts/templates/partial/user-card.mustache
  app/scripts/templates/sign_in.mustache
  app/scripts/templates/sign_in_password.mustache
  app/scripts/templates/sign_up_password.mustache
  app/scripts/views/index.js
  app/scripts/views/mixins/cached-credentials-mixin.js
  app/scripts/views/oauth_index.js
  app/scripts/views/sign_in.js
  app/scripts/views/sign_in_password.js
  app/scripts/views/sign_up_password.js
  app/tests/spec/models/auth_brokers/oauth.js
  app/tests/spec/views/index.js
  app/tests/spec/views/mixins/cached-credentials-mixin.js
  app/tests/spec/views/sign_in.js
  app/tests/spec/views/sign_in_password.js
  app/tests/spec/views/sign_up_password.js
  app/tests/test_start.js
  tests/functional/fx_firstrun_v2_email_first.js
  tests/functional/lib/helpers.js
  tests/functional/lib/selectors.js
  tests/functional/oauth_email_first.js
  tests/functional/oauth_handshake.js
  tests/functional/sign_in_cached.js
  tests/functional/sync_v3_email_first.js
Labels: waffle:review

#6403 fix(totp): remove totp experiment
  app/scripts/lib/experiments/grouping-rules/index.js
  app/scripts/lib/experiments/grouping-rules/totp.js
  app/scripts/models/auth_brokers/base.js
  app/scripts/views/behaviors/settings.js
  app/scripts/views/mixins/totp-experiment-mixin.js
  app/scripts/views/settings/two_step_authentication.js
  app/scripts/views/sign_in_totp_code.js
  app/tests/spec/lib/experiments/grouping-rules/index.js
  app/tests/spec/lib/experiments/grouping-rules/totp.js
  app/tests/spec/views/settings/two_step_authentication.js
  app/tests/test_start.js
  tests/functional/oauth_sign_in.js
  tests/functional/sign_in_recovery_code.js
  tests/functional/sign_in_totp.js
Labels: waffle:active

#6406 Uplift train-117 into master
  CHANGELOG.md
  app/scripts/lib/experiments/grouping-rules/index.js
  app/scripts/lib/experiments/grouping-rules/totp.js
  app/scripts/models/auth_brokers/base.js
  app/scripts/views/behaviors/settings.js
  app/scripts/views/mixins/totp-experiment-mixin.js
  app/scripts/views/settings/two_step_authentication.js
  app/scripts/views/sign_in_totp_code.js
  app/tests/spec/lib/experiments/grouping-rules/index.js
  app/tests/spec/lib/experiments/grouping-rules/totp.js
  app/tests/spec/views/settings/two_step_authentication.js
  app/tests/test_start.js
  package.json
  tests/functional/oauth_sign_in.js
  tests/functional/sign_in_recovery_code.js
  tests/functional/sign_in_totp.js
Labels: waffle:active
