Repository mozilla/fxa-content-server, pull requests merged in 2019-03, with the labels that each got.

#6999 feat(oauth): Add a devices/apps icon for Firefox Monitor.
  app/images/icon-service-monitor.svg
  app/styles/modules/_settings.scss
Labels: waffle:review

#7016 fix(metrics): reinstate entrypoint to the metrics context schema
  app/scripts/lib/metrics.js
  app/tests/spec/lib/metrics.js
  npm-shrinkwrap.json
  package.json
Labels: shipit, train-132, waffle:review

#7017 chore(release): Merge train-132 into master
  AUTHORS
  CHANGELOG.md
  package.json
Labels: waffle:active

#7014 fix(style): center the forgot password label
  app/scripts/templates/settings/change_password.mustache
Labels: train-133

#7007 style(avatar): added space between image and text
  app/styles/modules/_avatar.scss
Labels: train-133:qa-needed

#7020 feat(docker): Use node 10 in the Docker image.
  .travis.yml
  Dockerfile-build
Labels: waffle:active

#7035 chore(release): Merge private-Train 132 into public
  CHANGELOG.md
  npm-shrinkwrap.json
  server/lib/routes/get-metrics-flow.js
  server/lib/routes/post-metrics.js
  server/lib/validation.js
  tests/server/routes/get-metrics-flow.js
Labels: waffle:active

#7036 chore(release): Merge train-132 into master
  CHANGELOG.md
  npm-shrinkwrap.json
  package.json
  server/lib/routes/get-metrics-flow.js
  server/lib/routes/post-metrics.js
  server/lib/validation.js
  tests/server/routes/get-metrics-flow.js
Labels: waffle:active

#7034 fix(sync): Remove support for `context=fx_desktop_v2`
  app/scripts/lib/app-start.js
  app/scripts/models/auth_brokers/index.js
  app/tests/spec/lib/app-start.js
  app/tests/spec/models/auth_brokers/index.js
  app/tests/spec/models/user.js
  app/tests/spec/models/verification/same-browser.js
  server/lib/routes/get-index.js
  tests/functional.js
  tests/functional/confirm.js
  tests/functional/sync_v2.js
  tests/functional/sync_v2_force_auth.js
  tests/functional/sync_v2_reset_password.js
  tests/functional/sync_v2_settings.js
  tests/functional/sync_v2_sign_in.js
  tests/functional/sync_v2_sign_up.js
  tests/server/routes/get-index.js
Labels: waffle:active

#7047 chore(errors): add translated string for redis conflict errors
  app/scripts/lib/auth-errors.js
Labels: train-133, waffle:review

#6945 feat(feature-flags): wire in experiments to the feature-flag api
  .circleci/config.yml
  app/scripts/lib/app-start.js
  app/scripts/lib/config-loader.js
  app/scripts/lib/experiments/grouping-rules/communication-prefs.js
  app/scripts/lib/experiments/grouping-rules/index.js
  app/scripts/lib/experiments/grouping-rules/is-sampled-user.js
  app/scripts/lib/experiments/grouping-rules/send-sms-install-link.js
  app/scripts/lib/experiments/grouping-rules/sentry.js
  app/scripts/lib/experiments/grouping-rules/token-code.js
  app/tests/spec/lib/app-start.js
  app/tests/spec/lib/config-loader.js
  app/tests/spec/lib/experiments/grouping-rules/communication-prefs.js
  app/tests/spec/lib/experiments/grouping-rules/index.js
  app/tests/spec/lib/experiments/grouping-rules/is-sampled-user.js
  app/tests/spec/lib/experiments/grouping-rules/send-sms-install-link.js
  app/tests/spec/lib/experiments/grouping-rules/sentry.js
  app/tests/spec/lib/experiments/grouping-rules/token-code.js
  grunttasks/l10n-generate-pages.js
  npm-shrinkwrap.json
  package.json
  server/lib/configuration.js
  server/lib/routes/get-index.js
  server/templates/pages/src/index.html
  tests/server/routes/get-index.js
Labels: shipit, train-133, waffle:review

#7058 revert(feature-flags): remove feature-flagging
  .circleci/config.yml
  app/scripts/lib/app-start.js
  app/scripts/lib/config-loader.js
  app/scripts/lib/experiments/grouping-rules/communication-prefs.js
  app/scripts/lib/experiments/grouping-rules/index.js
  app/scripts/lib/experiments/grouping-rules/is-sampled-user.js
  app/scripts/lib/experiments/grouping-rules/send-sms-install-link.js
  app/scripts/lib/experiments/grouping-rules/sentry.js
  app/scripts/lib/experiments/grouping-rules/token-code.js
  app/tests/spec/lib/app-start.js
  app/tests/spec/lib/config-loader.js
  app/tests/spec/lib/experiments/grouping-rules/communication-prefs.js
  app/tests/spec/lib/experiments/grouping-rules/index.js
  app/tests/spec/lib/experiments/grouping-rules/is-sampled-user.js
  app/tests/spec/lib/experiments/grouping-rules/send-sms-install-link.js
  app/tests/spec/lib/experiments/grouping-rules/sentry.js
  app/tests/spec/lib/experiments/grouping-rules/token-code.js
  grunttasks/l10n-generate-pages.js
  npm-shrinkwrap.json
  package.json
  server/lib/configuration.js
  server/lib/routes/get-index.js
  server/templates/pages/src/index.html
  tests/server/routes/get-index.js
Labels: shipit, train-133, waffle:review

#7060 feat(feature-flags): wire in experiments to the feature-flag api
  .circleci/config.yml
  app/scripts/lib/app-start.js
  app/scripts/lib/config-loader.js
  app/scripts/lib/experiments/grouping-rules/communication-prefs.js
  app/scripts/lib/experiments/grouping-rules/index.js
  app/scripts/lib/experiments/grouping-rules/is-sampled-user.js
  app/scripts/lib/experiments/grouping-rules/send-sms-install-link.js
  app/scripts/lib/experiments/grouping-rules/sentry.js
  app/scripts/lib/experiments/grouping-rules/token-code.js
  app/tests/spec/lib/app-start.js
  app/tests/spec/lib/config-loader.js
  app/tests/spec/lib/experiments/grouping-rules/communication-prefs.js
  app/tests/spec/lib/experiments/grouping-rules/index.js
  app/tests/spec/lib/experiments/grouping-rules/is-sampled-user.js
  app/tests/spec/lib/experiments/grouping-rules/send-sms-install-link.js
  app/tests/spec/lib/experiments/grouping-rules/sentry.js
  app/tests/spec/lib/experiments/grouping-rules/token-code.js
  grunttasks/l10n-generate-pages.js
  npm-shrinkwrap.json
  package.json
  server/lib/configuration.js
  server/lib/routes/get-index.js
  server/templates/pages/src/index.html
  tests/server/routes/get-index.js
Labels: shipit, train-133, waffle:review

#7061 chore(release): Merge train-133 into master
  AUTHORS
  CHANGELOG.md
  package.json
Labels: waffle:active

#7064 fix(teamcity): npm ci all the things
  tests/teamcity/install-npm-deps.js
  tests/teamcity/install-npm-deps.sh
  tests/teamcity/run-server-resources.sh
  tests/teamcity/run-server.sh
Labels: waffle:active

#7065 feat(settings): add Fenix and Ref Browser icon
  app/styles/modules/_settings.scss
Labels: waffle:active

#7037 fix(auth_broker): fx-desktop-v1 merged into fx-ios-v1
  app/scripts/models/auth_brokers/fx-desktop-v1.js
  app/scripts/models/auth_brokers/fx-ios-v1.js
  app/tests/spec/models/auth_brokers/fx-desktop-v1.js
  app/tests/spec/models/auth_brokers/fx-ios-v1.js
  app/tests/test_start.js
Labels: train-134

#7038 style(settings): Added green banner for account recovery
  app/scripts/views/settings/account_recovery/confirm_password.js
  app/scripts/views/settings/account_recovery/confirm_revoke.js
  app/tests/spec/views/settings/account_recovery/confirm_password.js
  app/tests/spec/views/settings/account_recovery/confirm_revoke.js
Labels: train-134, waffle:blocked

#7086 fix(deps): update dependencies
  npm-shrinkwrap.json
  package.json
  tests/server/helpers/routesHelpers.js
Labels: waffle:active

#7077 feat(oauth): add oauth success screen
  app/scripts/lib/router.js
  app/scripts/lib/verification-reasons.js
  app/scripts/models/reliers/oauth.js
  app/scripts/views/ready.js
  app/tests/spec/models/reliers/oauth.js
  app/tests/spec/views/ready.js
  server/lib/routes.js
  server/lib/routes/get-oauth-success.js
  tests/functional/lib/selectors.js
  tests/functional/oauth_sign_up.js
  tests/server/routes/get-oauth-success.js
  tests/tests_server.js
Labels: train-134, waffle:review

#7081 feat(totp): Add loading indicator for session status verification
  app/scripts/templates/settings/two_step_authentication.mustache
  app/scripts/views/settings/two_step_authentication.js
Labels: train-134

#7073 fix(style): scale down larger customized qr-image for totp
  app/styles/modules/_settings-totp.scss
Labels: waffle:active

#7054 style(vpassword focused): verify password focused when switching from sign in to sign up
  app/scripts/templates/sign_up_password.mustache
  app/scripts/views/sign_up.js
  app/scripts/views/sign_up_password.js
  app/tests/spec/views/sign_up.js
  app/tests/spec/views/sign_up_password.js
Labels: waffle:active

#7018 feat(pairing): disable pairing for 2FA accounts
  app/scripts/lib/auth-errors.js
  app/scripts/views/pair/auth_allow.js
  app/scripts/views/pair/index.js
  app/scripts/views/pair/pairing-totp-mixin.js
  app/tests/spec/views/pair/auth_allow.js
  app/tests/spec/views/pair/index.js
  tests/functional/lib/selectors.js
  tests/functional/pairing.js
Labels: waffle:review

#7103 fix(style): add client icon for send in device list
  app/images/icon-service-send.svg
  app/styles/modules/_input-row.scss
  app/styles/modules/_settings.scss
Labels: waffle:review
