Repository mozilla/fxa-content-server, pull requests merged in 2019-02, with the labels that each got.

#6916 Uplift Train 129
  CHANGELOG.md
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#6921 feat(l10n): Enable Catalan (ca)
  npm-shrinkwrap.json
  package.json
Labels: waffle:review

#6903 Added suggest sync spacing
  app/styles/_state.scss
Labels: train-130, waffle:review

#6925 feat(pair): latest templates with strings
  app/scripts/templates/pair/supp.mustache
  app/scripts/templates/partial/device-being-paired.mustache
Labels: shipit, train-130, waffle:review

#6926 fix(test): Fix the change password tests.
  tests/functional/change_password.js
  tests/functional/sync_settings.js
Labels: shipit, train-130, waffle:active

#6935 fix(test): Fix the validation test failure.
  tests/server/validation.js
Labels: shipit, train-130, waffle:active

#6936 chore(release): Merge train-130 into master
  CHANGELOG.md
  package.json
Labels: waffle:active

#6937 fix(wrap): rewrap deps, update to latest point release of htmllint
  grunttasks/htmllint.js
  npm-shrinkwrap.json
Labels: waffle:active

#6939 fix(test): Fix the "change_password" test on teamcity.
  tests/functional/change_password.js
Labels: waffle:active

#6895 fix(sync): Remove support for context=fx_desktop_v1
  app/scripts/models/auth_brokers/index.js
  app/tests/spec/lib/app-start.js
  app/tests/spec/lib/metrics.js
  app/tests/spec/lib/router.js
  app/tests/spec/lib/storage-metrics.js
  app/tests/spec/models/auth_brokers/index.js
  app/tests/spec/models/reliers/sync.js
  app/tests/spec/models/verification/same-browser.js
  grunttasks/l10n-generate-pages.js
  npm-shrinkwrap.json
  package.json
  server/lib/amplitude.js
  server/lib/routes.js
  server/lib/routes/get-index.js
  server/lib/routes/get-update-firefox.js
  server/lib/routes/redirect-download-firefox.js
  server/lib/validation.js
  server/templates/pages/src/update_firefox.html
  tests/functional.js
  tests/functional/complete_sign_in.js
  tests/functional/fx_fennec_v1_sign_in.js
  tests/functional/fx_ios_v1_sign_in.js
  tests/functional/lib/selectors.js
  tests/functional/oauth_sync_sign_in.js
  tests/functional/sync_force_auth.js
  tests/functional/sync_reset_password.js
  tests/functional/sync_settings.js
  tests/functional/sync_sign_in.js
  tests/functional/sync_sign_up.js
  tests/functional/sync_v1.js
  tests/server/amplitude.js
  tests/server/routes/get-index.js
  tests/server/routes/get-update-firefox.js
  tests/server/routes/redirect-download-firefox.js
  tests/tests_server.js
  tests/tools/firefox_profile_creator.js
Labels: train-131, waffle:review

#6940 chore(release): Merge train 130 updates into master
  CHANGELOG.md
  package.json
  tests/functional/change_password.js
Labels: waffle:review

#6941 refactor(tests): eliminate duplicated setup code in app-start tests
  app/tests/spec/lib/app-start.js
Labels: train-131, waffle:review

#6927 feat(pair): pair views and brokers
  app/scripts/lib/app-start.js
  app/scripts/lib/channel-server-client.js
  app/scripts/lib/channels/web.js
  app/scripts/lib/constants.js
  app/scripts/lib/crypto/util.js
  app/scripts/lib/pairing-channel-client-errors.js
  app/scripts/lib/pairing-channel-client.js
  app/scripts/lib/router.js
  app/scripts/lib/vat.js
  app/scripts/models/auth_brokers/index.js
  app/scripts/models/auth_brokers/pairing/authority.js
  app/scripts/models/auth_brokers/pairing/remote-metadata.js
  app/scripts/models/auth_brokers/pairing/supplicant.js
  app/scripts/models/pairing/authority-state-machine.js
  app/scripts/models/pairing/state-machine.js
  app/scripts/models/pairing/state.js
  app/scripts/models/pairing/supplicant-state-machine.js
  app/scripts/models/reliers/oauth.js
  app/scripts/models/reliers/pairing/authority.js
  app/scripts/models/reliers/pairing/supplicant.js
  app/scripts/views/app.js
  app/scripts/views/pair/auth_allow.js
  app/scripts/views/pair/auth_complete.js
  app/scripts/views/pair/auth_wait_for_supp.js
  app/scripts/views/pair/device-being-paired-mixin.js
  app/scripts/views/pair/failure.js
  app/scripts/views/pair/index.js
  app/scripts/views/pair/success.js
  app/scripts/views/pair/supp.js
  app/scripts/views/pair/supp_allow.js
  app/scripts/views/pair/supp_wait_for_auth.js
  app/styles/modules/_custom-rows.scss
  app/styles/modules/_graphic.scss
  app/tests/mocks/pair.js
  app/tests/spec/lib/app-start.js
  app/tests/spec/lib/channel-server-client.js
  app/tests/spec/lib/channels/web.js
  app/tests/spec/lib/crypto/util.js
  app/tests/spec/lib/pairing-channel-client.js
  app/tests/spec/models/auth_brokers/pairing/authority.js
  app/tests/spec/models/auth_brokers/pairing/remote-metadata.js
  app/tests/spec/models/auth_brokers/pairing/supplicant.js
  app/tests/spec/models/pairing/authority-state-machine.js
  app/tests/spec/models/pairing/state-machine.js
  app/tests/spec/models/pairing/state.js
  app/tests/spec/models/pairing/supplicant-state-machine.js
  app/tests/spec/models/reliers/pairing/authority.js
  app/tests/spec/models/reliers/pairing/supplicant.js
  app/tests/spec/views/pair/auth_allow.js
  app/tests/spec/views/pair/auth_complete.js
  app/tests/spec/views/pair/auth_wait_for_supp.js
  app/tests/spec/views/pair/device-being-paired-mixin.js
  app/tests/spec/views/pair/failure.js
  app/tests/spec/views/pair/index.js
  app/tests/spec/views/pair/success.js
  app/tests/spec/views/pair/supp.js
  app/tests/spec/views/pair/supp_allow.js
  app/tests/spec/views/pair/supp_wait_for_auth.js
  app/tests/test_start.js
Labels: train-131, waffle:active

#6949 chore(deps): Update lodash, remove extend.
  npm-shrinkwrap.json
  package.json
  tests/server/helpers/routesHelpers.js
Labels: train-131, waffle:active

#6947 fix(test): Fix the Sync v1 tests.
  tests/functional/sync_v1.js
  tests/tools/firefox_profile_creator.js
Labels: train-131, waffle:active

#6953 chore(deps): update eslint-plugin-sorting to 0.4.0
  .eslintrc
  app/scripts/lib/key-codes.js
  app/scripts/models/auth_brokers/pairing/remote-metadata.js
  app/scripts/models/reliers/oauth.js
  app/scripts/views/connect_another_device.js
  app/tests/spec/lib/user-agent.js
  app/tests/spec/models/auth_brokers/pairing/authority.js
  app/tests/spec/models/auth_brokers/pairing/remote-metadata.js
  app/tests/spec/views/base.js
  app/tests/spec/views/pair/auth_allow.js
  app/tests/spec/views/pair/auth_complete.js
  app/tests/spec/views/pair/auth_wait_for_supp.js
  app/tests/spec/views/pair/device-being-paired-mixin.js
  app/tests/spec/views/pair/supp_allow.js
  app/tests/spec/views/pair/supp_wait_for_auth.js
  npm-shrinkwrap.json
  package.json
  server/lib/configuration.js
  server/lib/routes/post-metrics-errors.js
  server/lib/routes/post-metrics.js
  tests/functional/lib/selectors.js
  tests/functional/oauth_query_param_validation.js
Labels: train-131, waffle:review

#6958 fix(pairing): conver to Uint8Array for pairing channel compatibility
  app/scripts/lib/crypto/util.js
  app/scripts/lib/pairing-channel-client.js
  app/tests/spec/lib/crypto/util.js
Labels: waffle:active

#6963 fix(deps): Fix the npm audit advisories
  .nsprc
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#6948 feat(pairing): add pairing docs
  docs/architecture.md
  docs/images/pairing-flow1.png
  docs/images/pairing-flow2.png
  docs/pairing-architecture.md
Labels: P2, train-131, waffle:review

#6959 fix(css): update recovery key icon to grey90 a60
  app/images/recovery_key_key.svg
Labels: waffle:active

#6972 chore(templates): Add an issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: waffle:review

#6974 chore(release): Merge train-131 into master
  CHANGELOG.md
  package.json
Labels: waffle:active

#6975 chore(clients): Add Fenix to list of clients that can request oldsync scope
  server/lib/configuration.js
Labels: waffle:review

#6977 fix(teamcity): module extend is no longer used
  tests/teamcity/install-npm-deps.sh
Labels: waffle:active

#6985 feat(pairing): updated UX with the pair preferences button
  app/scripts/lib/channels/web.js
  app/scripts/lib/constants.js
  app/scripts/lib/router.js
  app/scripts/models/auth_brokers/base.js
  app/scripts/templates/pair/index.mustache
  app/scripts/templates/pair/unsupported.mustache
  app/scripts/views/pair/index.js
  app/scripts/views/pair/unsupported.js
  app/tests/spec/lib/channels/web.js
  app/tests/spec/models/auth_brokers/base.js
  app/tests/spec/views/pair/index.js
  app/tests/spec/views/pair/unsupported.js
  app/tests/test_start.js
Labels: waffle:review

#6995 chore(test): Test on node 10
  .travis.yml
Labels: waffle:active

#7000 Merge train-131 into master
  CHANGELOG.md
  package.json
  server/lib/configuration.js
Labels: train-131, waffle:active

#7003 fix(metrics): update amplitude events to mozlog 2 format
  server/lib/amplitude.js
  tests/server/amplitude.js
Labels: train-131, waffle:review

#7004 Merge train-131 into master
  CHANGELOG.md
  package.json
  server/lib/amplitude.js
  tests/server/amplitude.js
Labels: train-131, waffle:review

#6876 feat(pairing): enable pairing
  .circleci/config.yml
  app/scripts/lib/error-utils.js
  app/scripts/lib/fxa-pairing-channel.js
  app/scripts/lib/oauth-errors.js
  app/scripts/lib/pairing-channel-client.js
  app/scripts/models/auth_brokers/pairing/authority.js
  app/scripts/models/auth_brokers/pairing/supplicant.js
  app/tests/spec/models/auth_brokers/pairing/authority.js
  app/tests/spec/models/auth_brokers/pairing/remote-metadata.js
  app/tests/spec/models/auth_brokers/pairing/supplicant.js
  app/tests/spec/models/pairing/supplicant-state-machine.js
  app/tests/spec/views/pair/auth_allow.js
  app/tests/spec/views/pair/auth_complete.js
  app/tests/spec/views/pair/auth_wait_for_supp.js
  app/tests/spec/views/pair/supp_allow.js
  app/tests/spec/views/pair/supp_wait_for_auth.js
  npm-shrinkwrap.json
  package.json
  server/lib/configuration.js
  server/lib/csp/blocking.js
  server/lib/routes.js
  server/lib/routes/get-frontend-pairing.js
  server/lib/routes/get-frontend.js
  server/lib/routes/get-fxa-client-configuration.js
  server/lib/routes/get-index.js
  tests/functional/lib/selectors.js
  tests/functional/pairing.js
  tests/functional_pairing.js
  tests/intern.js
  tests/server/csp.js
  tests/server/routes/get-frontend-pairing.js
  tests/server/routes/get-fxa-client-configuration.js
  tests/server/routes/get-index.js
  tests/tests_server.js
  tests/tools/firefox_profile_creator.js
  webpack.config.js
Labels: shipit, train-132, waffle:active

#7010 fix(tests): move pairing preferences into their own block
  tests/tools/firefox_profile_creator.js
Labels: waffle:active
