Repository mozilla/fxa-content-server, pull requests merged in 2019-01, with the labels that each got.

#6853 fix(icons): add screenshots svg
  app/images/icon-service-screenshots.svg
  app/styles/modules/_settings.scss
Labels: waffle:active

#6749 update recovery length to 32 characters
  app/scripts/lib/constants.js
  app/styles/modules/_input-row.scss
  app/styles/modules/_settings-account-recovery.scss
Labels: waffle:review

#6856 Copy change to CWTS button
  app/scripts/templates/choose_what_to_sync.mustache
Labels: waffle:active

#6857 chore(docs): Clarify the `action` query param documentation.
  docs/query-params.md
Labels: waffle:active

#6858 fix(reset-password): No more error on /confirm_reset_password w/o initiating flow.
  app/scripts/views/confirm_reset_password.js
  app/tests/spec/views/confirm_reset_password.js
  tests/functional/lib/helpers.js
  tests/functional/reset_password.js
Labels: waffle:review

#6860 chore(modules): Convert several password related modules to es6 module format.
  app/scripts/views/elements/password-input.js
  app/scripts/views/mixins/password-mixin.js
  app/scripts/views/settings/change_password.js
  app/tests/spec/views/mixins/password-mixin.js
  app/tests/spec/views/settings/change_password.js
Labels: waffle:review

#6866 fix(teamcity): install with `npm ci`
  tests/teamcity/run.sh
Labels: waffle:active

#6865 fix(npm): use npm ci
  .circleci/config.yml
Labels: waffle:active

#6868 fix(metrics): ensure deviceId falls back to `none` if not set
  app/scripts/lib/metrics.js
  app/tests/spec/lib/metrics.js
Labels: train-128, waffle:review

#6870 fix(TOTP): Translate success status messages on /settings/recovery_codes
  app/scripts/views/mixins/save-options-mixin.js
  app/scripts/views/settings/recovery_codes.js
  app/scripts/views/settings/two_step_authentication.js
  app/tests/spec/views/mixins/save-options-mixin.js
  app/tests/spec/views/settings/recovery_codes.js
Labels: waffle:active

#6874 Wait for webchannel response in all cases
  app/scripts/lib/channel-server-client.js
  app/scripts/models/auth_brokers/pairing/authority.js
  app/scripts/models/reliers/pairing/supplicant.js
Labels: waffle:active

#6872 fix(l10n): Ensure tooltips are translated in local dev
  app/scripts/views/form.js
  app/tests/spec/views/form.js
Labels: waffle:review

#6883 chore(deps): Update to fxa-shared@1.0.15
  npm-shrinkwrap.json
  package.json
Labels: train-129, waffle:review

#6885 feat(change-password): Add a "verification password" on password change.
  app/scripts/templates/settings/change_password.mustache
  app/scripts/templates/test_template.mustache
  app/scripts/views/mixins/password-mixin.js
  app/scripts/views/settings/change_password.js
  app/tests/spec/views/mixins/password-mixin.js
  app/tests/spec/views/settings/change_password.js
  tests/functional/change_password.js
  tests/functional/lib/helpers.js
Labels: waffle:review

#6886 fix(metrics): allow optional platform in /metrics-errors
  server/lib/routes/post-metrics-errors.js
  tests/server/metrics-errors.js
Labels: waffle:active

#6888 fix(sign_in_code): fix code numeric input
  app/scripts/templates/sign_in_token_code.mustache
Labels: waffle:active

#6887 feat(npm): rewrap npm deps to pick up latest eslint-plugin-fxa rules
  npm-shrinkwrap.json
  package.json
Labels: waffle:active

#6882 feat(settings): put communication prefs behind a feature flag
  app/scripts/lib/app-start.js
  app/scripts/views/mixins/email-opt-in-mixin.js
  app/scripts/views/settings.js
  app/tests/spec/views/mixins/email-opt-in-mixin.js
  app/tests/spec/views/settings.js
  server/lib/configuration.js
  server/lib/routes/get-index.js
Labels: waffle:review

#6891 fix(pw-strength): Use 15px font size in pw-strength meter for Arabic.
  app/styles/modules/_password-row.scss
Labels: shipit, train-129, waffle:review

#6892 chore(release): Merge train-129 into master
  AUTHORS
  CHANGELOG.md
  package.json
Labels: waffle:review

#6897 fix(channel-client): remove unused errors
  app/scripts/lib/channel-server-client-errors.js
  app/tests/spec/lib/channel-server-client.js
Labels: waffle:active

#6896 fix(start): do not add extra history item when choosing start page
  app/scripts/lib/app-start.js
  app/tests/spec/lib/app-start.js
Labels: waffle:active

#6884 fix(oauth): fix scope validation on empty scopes
  app/scripts/models/reliers/oauth.js
  app/tests/spec/models/reliers/oauth.js
Labels: train-130, waffle:review

#6902 fix(forms): attach events for base view and child views
  app/scripts/views/form.js
  app/tests/spec/views/form.js
Labels: waffle:review

#6901 feat(pair): add pair templates and graphics
  app/images/graphic_hearts_broken.svg
  app/scripts/templates/pair/auth_allow.mustache
  app/scripts/templates/pair/auth_complete.mustache
  app/scripts/templates/pair/auth_wait_for_supp.mustache
  app/scripts/templates/pair/failure.mustache
  app/scripts/templates/pair/index.mustache
  app/scripts/templates/pair/success.mustache
  app/scripts/templates/pair/supp.mustache
  app/scripts/templates/pair/supp_allow.mustache
  app/scripts/templates/pair/supp_wait_for_auth.mustache
Labels: waffle:review

#6899 chore(server): build extra templates for Mozilla China
  grunttasks/build.js
  grunttasks/copy.js
  server/lib/configuration.js
  server/lib/localized-render.js
Labels: train-130, waffle:active

#6893 chore(token-codes): Enroll Reference Browser in the token codes experiment
  app/scripts/lib/experiments/grouping-rules/token-code.js
Labels: waffle:backlog, waffle:review

#6911 fix(logging): Ensure screen.width and screen.height are numbers
  server/lib/metrics-collector-stderr.js
  tests/server/metrics-collector-stderr.js
Labels: waffle:active

#6859 feat(pw-strength): Add pw-strength balloon to password change.
  app/scripts/models/password_strength/password_strength_balloon.js
  app/scripts/templates/partial/password-strength-balloon.mustache
  app/scripts/templates/settings/change_password.mustache
  app/scripts/views/elements/jquery-plugin.js
  app/scripts/views/form.js
  app/scripts/views/mixins/password-strength-mixin.js
  app/scripts/views/password_strength/password_strength_balloon.js
  app/scripts/views/password_strength/password_with_strength_balloon.js
  app/scripts/views/settings/change_password.js
  app/styles/modules/_password-row.scss
  app/tests/spec/models/password_strength/password_strength_balloon.js
  app/tests/spec/views/mixins/password-strength-mixin.js
  app/tests/spec/views/password_strength/password_strength_balloon.js
  app/tests/spec/views/password_strength/password_with_strength_balloon.js
  app/tests/spec/views/settings/change_password.js
  app/tests/spec/views/sign_up_password.js
  tests/functional/change_password.js
  tests/functional/lib/helpers.js
  tests/functional/lib/selectors.js
Labels: train-130, waffle:review

#6913 fix(tests): fix tests for latest geckodriver compat
  tests/functional/password_visibility.js
  tests/functional/sync_sign_up.js
Labels: waffle:active

#6915 fix(metrics): Fix entrypoint being overwritten for every event.
  npm-shrinkwrap.json
  package.json
Labels: waffle:active
